// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
use crate::types::{AssetInfo, EModeConfig};
use alloy_primitives::{address, Address};

// IPoolAddressesProvider https://optimistic.etherscan.io/address/0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb
pub const POOL_ADDRESSES_PROVIDER: Address = address!("0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb");

// IPool https://optimistic.etherscan.io/address/0x794a61358D6845594F94dc1DB02A252b5b4814aD
pub const POOL: Address = address!("0x794a61358D6845594F94dc1DB02A252b5b4814aD");

// IPoolConfigurator https://optimistic.etherscan.io/address/0x8145eddDf43f50276641b55bd3AD95944510021E
pub const POOL_CONFIGURATOR: Address = address!("0x8145eddDf43f50276641b55bd3AD95944510021E");

// IAaveOracle https://optimistic.etherscan.io/address/0xD81eb3728a631871a7eBBaD631b5f424909f0c77
pub const ORACLE: Address = address!("0xD81eb3728a631871a7eBBaD631b5f424909f0c77");

// https://optimistic.etherscan.io/address/0xE229d5DE4BD5beEAf12d427B5B57BFe66abD2c3b
pub const PRICE_ORACLE_SENTINEL: Address = address!("0xE229d5DE4BD5beEAf12d427B5B57BFe66abD2c3b");

// https://optimistic.etherscan.io/address/0x746c675dAB49Bcd5BB9Dc85161f2d7Eb435009bf
pub const ACL_ADMIN: Address = address!("0x746c675dAB49Bcd5BB9Dc85161f2d7Eb435009bf");

// IACLManager https://optimistic.etherscan.io/address/0xa72636CbcAa8F5FF95B2cc47F3CDEe83F3294a0B
pub const ACL_MANAGER: Address = address!("0xa72636CbcAa8F5FF95B2cc47F3CDEe83F3294a0B");

// IPoolDataProvider https://optimistic.etherscan.io/address/0x14496b405D62c24F91f04Cda1c69Dc526D56fDE5
pub const AAVE_PROTOCOL_DATA_PROVIDER: Address =
  address!("0x14496b405D62c24F91f04Cda1c69Dc526D56fDE5");

// https://optimistic.etherscan.io/address/0x7f775bb7af2e7E09D5Dc9506c95516159a5cA0D0
pub const POOL_IMPL: Address = address!("0x7f775bb7af2e7E09D5Dc9506c95516159a5cA0D0");

// https://optimistic.etherscan.io/address/0xE5e48Ad1F9D1A894188b483DcF91f4FaD6AbA43b
pub const POOL_CONFIGURATOR_IMPL: Address = address!("0xE5e48Ad1F9D1A894188b483DcF91f4FaD6AbA43b");

// https://optimistic.etherscan.io/address/0x929EC64c34a17401F460460D4B9390518E5B473e
pub const DEFAULT_INCENTIVES_CONTROLLER: Address =
  address!("0x929EC64c34a17401F460460D4B9390518E5B473e");

// https://optimistic.etherscan.io/address/0x048f2228D7Bf6776f99aB50cB1b1eaB4D1d4cA73
pub const EMISSION_MANAGER: Address = address!("0x048f2228D7Bf6776f99aB50cB1b1eaB4D1d4cA73");

// ICollector https://optimistic.etherscan.io/address/0xB2289E329D2F85F1eD31Adbb30eA345278F21bcf
pub const COLLECTOR: Address = address!("0xB2289E329D2F85F1eD31Adbb30eA345278F21bcf");

// https://optimistic.etherscan.io/address/0xbCb167bDCF14a8F791d6f4A6EDd964aed2F8813B
pub const DEFAULT_A_TOKEN_IMPL_REV_2: Address =
  address!("0xbCb167bDCF14a8F791d6f4A6EDd964aed2F8813B");

// https://optimistic.etherscan.io/address/0x04a8D477eE202aDCE1682F5902e1160455205b12
pub const DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_2: Address =
  address!("0x04a8D477eE202aDCE1682F5902e1160455205b12");

// https://optimistic.etherscan.io/address/0x5E76E98E0963EcDC6A065d1435F84065b7523f39
pub const CAPS_PLUS_RISK_STEWARD: Address = address!("0x5E76E98E0963EcDC6A065d1435F84065b7523f39");

// https://optimistic.etherscan.io/address/0x928807b90A74210268B590D0159FCf1340Ad76Bd
pub const RISK_STEWARD: Address = address!("0x928807b90A74210268B590D0159FCf1340Ad76Bd");

// https://optimistic.etherscan.io/address/0x3829943c53F2d00e20B58475aF19716724bF90Ba
pub const FREEZING_STEWARD: Address = address!("0x3829943c53F2d00e20B58475aF19716724bF90Ba");

// https://optimistic.etherscan.io/address/0xE28E2c8d240dd5eBd0adcab86fbD79df7a052034
pub const DEBT_SWAP_ADAPTER: Address = address!("0xE28E2c8d240dd5eBd0adcab86fbD79df7a052034");

// https://optimistic.etherscan.io/address/0x9abADECD08572e0eA5aF4d47A9C7984a5AA503dC
pub const L2_ENCODER: Address = address!("0x9abADECD08572e0eA5aF4d47A9C7984a5AA503dC");

// https://optimistic.etherscan.io/address/0x1AA25FdD7d55FA8a401D6EFba8e48874Ef730E55
pub const CONFIG_ENGINE: Address = address!("0x1AA25FdD7d55FA8a401D6EFba8e48874Ef730E55");

// https://optimistic.etherscan.io/address/0x770ef9f4fe897e59daCc474EF11238303F9552b6
pub const POOL_ADDRESSES_PROVIDER_REGISTRY: Address =
  address!("0x770ef9f4fe897e59daCc474EF11238303F9552b6");

// https://optimistic.etherscan.io/address/0x5d4D4007A4c6336550DdAa2a7c0d5e7972eebd16
pub const REPAY_WITH_COLLATERAL_ADAPTER: Address =
  address!("0x5d4D4007A4c6336550DdAa2a7c0d5e7972eebd16");

// https://optimistic.etherscan.io/address/0x22D76094730fA377184100EFB8CEfC673B89B372
pub const LEGACY_STATIC_A_TOKEN_FACTORY: Address =
  address!("0x22D76094730fA377184100EFB8CEfC673B89B372");

// https://optimistic.etherscan.io/address/0x830C5A67a0C95D69dA5fb7801Ac1773c6fB53857
pub const SWAP_COLLATERAL_ADAPTER: Address = address!("0x830C5A67a0C95D69dA5fb7801Ac1773c6fB53857");

// https://optimistic.etherscan.io/address/0x5c5228aC8BC1528482514aF3e27E692495148717
pub const UI_INCENTIVE_DATA_PROVIDER: Address =
  address!("0x5c5228aC8BC1528482514aF3e27E692495148717");

// https://optimistic.etherscan.io/address/0xE92cd6164CE7DC68e740765BC1f2a091B6CBc3e4
pub const UI_POOL_DATA_PROVIDER: Address = address!("0xE92cd6164CE7DC68e740765BC1f2a091B6CBc3e4");

// https://optimistic.etherscan.io/address/0xBc790382B3686abffE4be14A030A96aC6154023a
pub const WALLET_BALANCE_PROVIDER: Address = address!("0xBc790382B3686abffE4be14A030A96aC6154023a");

// https://optimistic.etherscan.io/address/0x5f2508cAE9923b02316254026CD43d7902866725
pub const WETH_GATEWAY: Address = address!("0x5f2508cAE9923b02316254026CD43d7902866725");

// https://optimistic.etherscan.io/address/0x78F8Bd884C3D738B74B420540659c82f392820e0
pub const WITHDRAW_SWAP_ADAPTER: Address = address!("0x78F8Bd884C3D738B74B420540659c82f392820e0");

// https://optimistic.etherscan.io/address/0x170d6D6FCAbF0Ba3932a03d5f470c16c39c18e39
pub const STATA_FACTORY: Address = address!("0x170d6D6FCAbF0Ba3932a03d5f470c16c39c18e39");

// https://optimistic.etherscan.io/address/0x9601de16a38B6d2Dd5d5f313EEDb4fcAf9718D6C
pub const DUST_BIN: Address = address!("0x9601de16a38B6d2Dd5d5f313EEDb4fcAf9718D6C");

// https://optimistic.etherscan.io/address/0xD835fb6f9823b4054Ccf30403De76AA8abcd00b8
pub const CLINIC_STEWARD: Address = address!("0xD835fb6f9823b4054Ccf30403De76AA8abcd00b8");

// https://optimistic.etherscan.io/address/0x4684b645386525057526EB85854045914Fe389d6
pub const POOL_EXPOSURE_STEWARD: Address = address!("0x4684b645386525057526EB85854045914Fe389d6");

pub const CHAIN_ID: u32 = 10;

pub const ASSETS: &[AssetInfo] = &[
  AssetInfo {
    name: "DAI",
    decimals: 18,
    id: 0,
    underlying: address!("0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"),
    a_token: address!("0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE"),
    v_token: address!("0x8619d80FB0141ba7F184CbF22fd724116D9f7ffC"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x1a96fe91278bcF6F19665F642FE7a88cD5c360bb"),
    static_a_token: Some(address!("0x6dDc64289bE8a71A707fB057d5d07Cc756055d6e")),
    stata_token: Some(address!("0x61b620FAd391b53A2D0973b10a3Ed69558d5c66E")),
  },
  AssetInfo {
    name: "LINK",
    decimals: 18,
    id: 1,
    underlying: address!("0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6"),
    a_token: address!("0x191c10Aa4AF7C30e871E70C95dB0E4eb77237530"),
    v_token: address!("0x953A573793604aF8d41F306FEb8274190dB4aE0e"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0xCc232dcFAAE6354cE191Bd574108c1aD03f86450"),
    static_a_token: Some(address!("0x39BCf217ACc4Bf2fCaF7BC8800E69D986912c75e")),
    stata_token: None,
  },
  AssetInfo {
    name: "USDC",
    decimals: 6,
    id: 2,
    underlying: address!("0x7F5c764cBc14f9669B88837ca1490cCa17c31607"),
    a_token: address!("0x625E7708f30cA75bfd92586e17077590C60eb4cD"),
    v_token: address!("0xFCCf3cAbbe80101232d343252614b6A3eE81C989"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x2daA7078f78485A708003989cBc9a643e3b4B61f"),
    static_a_token: Some(address!("0x9F281eb58fd98ad98EDe0fc4C553AD4D73e7Ca2C")),
    stata_token: None,
  },
  AssetInfo {
    name: "WBTC",
    decimals: 8,
    id: 3,
    underlying: address!("0x68f180fcCe6836688e9084f035309E29Bf0A2095"),
    a_token: address!("0x078f358208685046a11C85e8ad32895DED33A249"),
    v_token: address!("0x92b42c66840C7AD907b4BF74879FF3eF7c529473"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0xD702DD976Fb76Fffc2D3963D037dfDae5b04E593"),
    static_a_token: Some(address!("0x6d998FeEFC7B3664eaD09CAf02b5a0fc2E365F18")),
    stata_token: None,
  },
  AssetInfo {
    name: "WETH",
    decimals: 18,
    id: 4,
    underlying: address!("0x4200000000000000000000000000000000000006"),
    a_token: address!("0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8"),
    v_token: address!("0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x13e3Ee699D1909E989722E753853AE30b17e08c5"),
    static_a_token: Some(address!("0x98d69620C31869fD4822ceb6ADAB31180475FD37")),
    stata_token: Some(address!("0x464b808c2C7E04b07e860fDF7a91870620246148")),
  },
  AssetInfo {
    name: "USDT",
    decimals: 6,
    id: 5,
    underlying: address!("0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"),
    a_token: address!("0x6ab707Aca953eDAeFBc4fD23bA73294241490620"),
    v_token: address!("0xfb00AC187a8Eb5AFAE4eACE434F493Eb62672df7"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x70E6DBBFFc9c3c6fB4a9c349E3101B7dCEE67f4D"),
    static_a_token: Some(address!("0x035c93db04E5aAea54E6cd0261C492a3e0638b37")),
    stata_token: Some(address!("0x927CfF131fD5B43FC992D071929b2c095d6E4b70")),
  },
  AssetInfo {
    name: "AAVE",
    decimals: 18,
    id: 6,
    underlying: address!("0x76FB31fb4af56892A25e32cFC43De717950c9278"),
    a_token: address!("0xf329e36C7bF6E5E86ce2150875a84Ce77f477375"),
    v_token: address!("0xE80761Ea617F66F96274eA5e8c37f03960ecC679"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x338ed6787f463394D24813b297401B9F05a8C9d1"),
    static_a_token: Some(address!("0xae0Ca1B1Bc6cac26981B5e2b9c40f8Ce8A9082eE")),
    stata_token: None,
  },
  AssetInfo {
    name: "sUSD",
    decimals: 18,
    id: 7,
    underlying: address!("0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9"),
    a_token: address!("0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97"),
    v_token: address!("0x4a1c3aD6Ed28a636ee1751C69071f6be75DEb8B8"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0xC77E9CF9603F5ef5503213229ABB1Fec3001f312"),
    static_a_token: Some(address!("0x3A956E2Fcc7e71Ea14b0257d40BEbdB287d19652")),
    stata_token: None,
  },
  AssetInfo {
    name: "OP",
    decimals: 18,
    id: 8,
    underlying: address!("0x4200000000000000000000000000000000000042"),
    a_token: address!("0x513c7E3a9c69cA3e22550eF58AC1C0088e918FFf"),
    v_token: address!("0x77CA01483f379E58174739308945f044e1a764dc"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x0D276FC14719f9292D5C1eA2198673d1f4269246"),
    static_a_token: Some(address!("0xd4F1Cf9A038269FE8F03745C2875591Ad6438ab1")),
    stata_token: None,
  },
  AssetInfo {
    name: "wstETH",
    decimals: 18,
    id: 9,
    underlying: address!("0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb"),
    a_token: address!("0xc45A479877e1e9Dfe9FcD4056c699575a1045dAA"),
    v_token: address!("0x34e2eD44EF7466D5f9E0b782B5c08b57475e7907"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x724E47194d97263ccb71FDad84b4fed18a8be387"),
    static_a_token: Some(address!("0xb972abef80046A57409e37a7DF5dEf2638917516")),
    stata_token: None,
  },
  AssetInfo {
    name: "LUSD",
    decimals: 18,
    id: 10,
    underlying: address!("0xc40F949F8a4e094D1b49a23ea9241D289B7b2819"),
    a_token: address!("0x8Eb270e296023E9D92081fdF967dDd7878724424"),
    v_token: address!("0xCE186F6Cccb0c955445bb9d10C59caE488Fea559"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x8f4dAFb6Feb190e7846eb7665fD49FFb1177Ff8e"),
    static_a_token: Some(address!("0x84648dc3Cefb601bc28a49A07a1A8Bad04D30Ad3")),
    stata_token: None,
  },
  AssetInfo {
    name: "MAI",
    decimals: 18,
    id: 11,
    underlying: address!("0xdFA46478F9e5EA86d57387849598dbFB2e964b02"),
    a_token: address!("0x8ffDf2DE812095b1D19CB146E4c004587C0A0692"),
    v_token: address!("0xA8669021776Bc142DfcA87c21b4A52595bCbB40a"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0xc6ac65E8f4F50a6655Efd78A92b6c503B5B625C8"),
    static_a_token: Some(address!("0x60495bC8D8Baf7E866888ecC00491e37B47dfF24")),
    stata_token: None,
  },
  AssetInfo {
    name: "rETH",
    decimals: 18,
    id: 12,
    underlying: address!("0x9Bcef72be871e61ED4fBbc7630889beE758eb81D"),
    a_token: address!("0x724dc807b04555b71ed48a6896b6F41593b8C637"),
    v_token: address!("0xf611aEb5013fD2c0511c9CD55c7dc5C1140741A6"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0xF17e75D58D4Be71B8e674fA104B71a827e38F087"),
    static_a_token: Some(address!("0xf9ce3c97b4b54F3D16861420f4816D9f68190B7B")),
    stata_token: None,
  },
  AssetInfo {
    name: "USDCn",
    decimals: 6,
    id: 13,
    underlying: address!("0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"),
    a_token: address!("0x38d693cE1dF5AaDF7bC62595A37D667aD57922e5"),
    v_token: address!("0x5D557B07776D12967914379C71a1310e917C7555"),
    interest_rate_strategy: address!("0x9359282735496463131139875849d5302Fb4bed1"),
    oracle: address!("0x2daA7078f78485A708003989cBc9a643e3b4B61f"),
    static_a_token: Some(address!("0x4DD03dfD36548C840B563745e3FBeC320F37BA7e")),
    stata_token: Some(address!("0x41B334E9F2C0ED1f30fD7c351874a6071C53a78E")),
  },
];

pub const E_MODES: &[EModeConfig] = &[
  EModeConfig {
    id: 1,
    label: "Stablecoins",
    collateral_bitmap: "8357",
    collateral_assets: &[
      address!("0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"),
      address!("0x7F5c764cBc14f9669B88837ca1490cCa17c31607"),
      address!("0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"),
      address!("0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9"),
      address!("0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"),
    ],
    borrowable_bitmap: "8357",
    borrowable_assets: &[
      address!("0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"),
      address!("0x7F5c764cBc14f9669B88837ca1490cCa17c31607"),
      address!("0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"),
      address!("0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9"),
      address!("0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"),
    ],
    ltv: 1,
    liquidation_threshold: 8700,
    liquidation_bonus: 10100,
  },
  EModeConfig {
    id: 2,
    label: "ETH correlated",
    collateral_bitmap: "4624",
    collateral_assets: &[
      address!("0x4200000000000000000000000000000000000006"),
      address!("0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb"),
      address!("0x9Bcef72be871e61ED4fBbc7630889beE758eb81D"),
    ],
    borrowable_bitmap: "4624",
    borrowable_assets: &[
      address!("0x4200000000000000000000000000000000000006"),
      address!("0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb"),
      address!("0x9Bcef72be871e61ED4fBbc7630889beE758eb81D"),
    ],
    ltv: 9300,
    liquidation_threshold: 9500,
    liquidation_bonus: 10100,
  },
];
