# include .env file and export its env vars
# (-include to ignore error if it does not exist)
-include .env

# deps
update:; forge update

# Build & test
build  :; forge build --sizes
test   :; forge test -vvv
trace   :; forge test -vvvv
clean  :; forge clean
snapshot :; forge snapshot