// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3EthereumLido {
  // https://etherscan.io/address/0xcfBf336fe147D643B9Cb705648500e101504B16d
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xcfBf336fe147D643B9Cb705648500e101504B16d);

  // https://etherscan.io/address/0x4e033931ad43597d96D6bcc25c280717730B58B1
  IPool internal constant POOL = IPool(0x4e033931ad43597d96D6bcc25c280717730B58B1);

  // https://etherscan.io/address/0x342631c6CeFC9cfbf97b2fe4aa242a236e1fd517
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x342631c6CeFC9cfbf97b2fe4aa242a236e1fd517);

  // https://etherscan.io/address/0xE3C061981870C0C7b1f3C4F4bB36B95f1F260BE6
  IAaveOracle internal constant ORACLE = IAaveOracle(0xE3C061981870C0C7b1f3C4F4bB36B95f1F260BE6);

  // https://etherscan.io/address/0x5300A1a15135EA4dc7aD5a167152C01EFc9b192A
  address internal constant ACL_ADMIN = 0x5300A1a15135EA4dc7aD5a167152C01EFc9b192A;

  // https://etherscan.io/address/0x013E2C7567b6231e865BB9273F8c7656103611c0
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x013E2C7567b6231e865BB9273F8c7656103611c0);

  // https://etherscan.io/address/0xB85B2bFEbeC4F5f401dbf92ac147A3076391fCD5
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xB85B2bFEbeC4F5f401dbf92ac147A3076391fCD5);

  // https://etherscan.io/address/0xEf534b9Ad7F185aff4146750da6bf8Bb7f58020C
  address internal constant POOL_IMPL = 0xEf534b9Ad7F185aff4146750da6bf8Bb7f58020C;

  // https://etherscan.io/address/0x5793FE4de34532F162B4e207aF872729880ec2b6
  address internal constant POOL_CONFIGURATOR_IMPL = 0x5793FE4de34532F162B4e207aF872729880ec2b6;

  // https://etherscan.io/address/0x8164Cc65827dcFe994AB23944CBC90e0aa80bFcb
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x8164Cc65827dcFe994AB23944CBC90e0aa80bFcb;

  // https://etherscan.io/address/0x223d844fc4B006D67c0cDbd39371A9F73f69d974
  address internal constant EMISSION_MANAGER = 0x223d844fc4B006D67c0cDbd39371A9F73f69d974;

  // https://etherscan.io/address/0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
  ICollector internal constant COLLECTOR = ICollector(0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c);

  // https://etherscan.io/address/0xe7525bfE967412b6bAF2E2310cdeeaeFDD8f86Ed
  address internal constant DEFAULT_A_TOKEN_IMPL = 0xe7525bfE967412b6bAF2E2310cdeeaeFDD8f86Ed;

  // https://etherscan.io/address/0xF9c86ADF20b55b816aDc094bd9C0AeCe7D7E309c
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0xF9c86ADF20b55b816aDc094bd9C0AeCe7D7E309c;

  // https://etherscan.io/address/0xC6cAB8D39D93DC0Bd5986E7Ce5Bb956E30103A43
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0xC6cAB8D39D93DC0Bd5986E7Ce5Bb956E30103A43;

  // https://etherscan.io/address/0x66E1aBdb06e7363a618D65a910c540dfED23754f
  address internal constant REPAY_WITH_COLLATERAL_ADAPTER =
    0x66E1aBdb06e7363a618D65a910c540dfED23754f;

  // https://etherscan.io/address/0xD0887AA7fEBC8962c622493646195e7c76D94fCE
  address internal constant SWAP_COLLATERAL_ADAPTER = 0xD0887AA7fEBC8962c622493646195e7c76D94fCE;

  // https://etherscan.io/address/0x43eDB797834151D041619EEF833Edc784B509dAE
  address internal constant WITHDRAW_SWAP_ADAPTER = 0x43eDB797834151D041619EEF833Edc784B509dAE;

  // https://etherscan.io/address/0xe3dFf4052F0bF6134ACb73bEaE8fe2317d71F047
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xe3dFf4052F0bF6134ACb73bEaE8fe2317d71F047;

  // https://etherscan.io/address/0x3F78BBD206e4D3c504Eb854232EdA7e47E9Fd8FC
  address internal constant UI_POOL_DATA_PROVIDER = 0x3F78BBD206e4D3c504Eb854232EdA7e47E9Fd8FC;

  // https://etherscan.io/address/0xC7be5307ba715ce89b152f3Df0658295b3dbA8E2
  address internal constant WALLET_BALANCE_PROVIDER = 0xC7be5307ba715ce89b152f3Df0658295b3dbA8E2;

  // https://etherscan.io/address/0x3167C452fA3fa1e5C16bB83Bc0fde4519C464299
  address internal constant WETH_GATEWAY = 0x3167C452fA3fa1e5C16bB83Bc0fde4519C464299;

  // https://etherscan.io/address/0x88d42CFe16d097e149881216EE90fD1729e4322d
  address internal constant CONFIG_ENGINE = 0x88d42CFe16d097e149881216EE90fD1729e4322d;

  // https://etherscan.io/address/0x7e6a6B115D31d4A837E3C737c49Cf6Fafe6112C3
  address internal constant RISK_STEWARD = 0x7e6a6B115D31d4A837E3C737c49Cf6Fafe6112C3;

  // https://etherscan.io/address/0xd1B2dec98A95B773C4909B5CD8FB455F467A527f
  address internal constant DEBT_SWAP_ADAPTER = 0xd1B2dec98A95B773C4909B5CD8FB455F467A527f;

  // https://etherscan.io/address/0x81aFd0F99c2Afa2f2DD7E387c2Ef9CD2a29b6E1A
  address internal constant EDGE_RISK_STEWARD_RATES = 0x81aFd0F99c2Afa2f2DD7E387c2Ef9CD2a29b6E1A;

  // https://etherscan.io/address/0x834a5aC6e9D05b92F599A031941262F761c34859
  address internal constant EDGE_INJECTOR_RATES = 0x834a5aC6e9D05b92F599A031941262F761c34859;

  // https://etherscan.io/address/0x347C75d19718a05148687E13dca259aD016aB411
  address internal constant STATA_FACTORY = 0x347C75d19718a05148687E13dca259aD016aB411;

  // https://etherscan.io/address/0x2cE01c87Fec1b71A9041c52CaED46Fc5f4807285
  address internal constant GHO_DIRECT_MINTER = 0x2cE01c87Fec1b71A9041c52CaED46Fc5f4807285;

  // https://etherscan.io/address/0x31a0Ba3C2242a095dBF58A7C53751eCBd27dBA9b
  address internal constant DUST_BIN = 0x31a0Ba3C2242a095dBF58A7C53751eCBd27dBA9b;

  // https://etherscan.io/address/0x7571F419F7Df2d0622C1A20154a0D4250B2265cC
  address internal constant CLINIC_STEWARD = 0x7571F419F7Df2d0622C1A20154a0D4250B2265cC;

  // https://etherscan.io/address/0x84f2C90f2D66E700baA4CF3cbF66bE7D8f21Bd87
  address internal constant SVR_STEWARD = 0x84f2C90f2D66E700baA4CF3cbF66bE7D8f21Bd87;
}
library AaveV3EthereumLidoAssets {
  // https://etherscan.io/address/0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
  address internal constant wstETH_UNDERLYING = 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0;

  uint8 internal constant wstETH_DECIMALS = 18;

  // https://etherscan.io/address/0xC035a7cf15375cE2706766804551791aD035E0C2
  address internal constant wstETH_A_TOKEN = 0xC035a7cf15375cE2706766804551791aD035E0C2;

  // https://etherscan.io/address/0xE439edd2625772AA635B437C099C607B6eb7d35f
  address internal constant wstETH_V_TOKEN = 0xE439edd2625772AA635B437C099C607B6eb7d35f;

  // https://etherscan.io/address/0xe1D97bF61901B075E9626c8A2340a7De385861Ef
  address internal constant wstETH_ORACLE = 0xe1D97bF61901B075E9626c8A2340a7De385861Ef;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant wstETH_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0x775F661b0bD1739349b9A2A3EF60be277c5d2D29
  address internal constant wstETH_STATA_TOKEN = 0x775F661b0bD1739349b9A2A3EF60be277c5d2D29;

  // https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
  address internal constant WETH_UNDERLYING = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://etherscan.io/address/0xfA1fDbBD71B0aA16162D76914d69cD8CB3Ef92da
  address internal constant WETH_A_TOKEN = 0xfA1fDbBD71B0aA16162D76914d69cD8CB3Ef92da;

  // https://etherscan.io/address/0x91b7d78BF92db564221f6B5AeE744D1727d1Dd1e
  address internal constant WETH_V_TOKEN = 0x91b7d78BF92db564221f6B5AeE744D1727d1Dd1e;

  // https://etherscan.io/address/0x5424384B256154046E9667dDFaaa5e550145215e
  address internal constant WETH_ORACLE = 0x5424384B256154046E9667dDFaaa5e550145215e;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0x0FE906e030a44eF24CA8c7dC7B7c53A6C4F00ce9
  address internal constant WETH_STATA_TOKEN = 0x0FE906e030a44eF24CA8c7dC7B7c53A6C4F00ce9;

  // https://etherscan.io/address/0xdC035D45d973E3EC169d2276DDab16f1e407384F
  address internal constant USDS_UNDERLYING = 0xdC035D45d973E3EC169d2276DDab16f1e407384F;

  uint8 internal constant USDS_DECIMALS = 18;

  // https://etherscan.io/address/0x09AA30b182488f769a9824F15E6Ce58591Da4781
  address internal constant USDS_A_TOKEN = 0x09AA30b182488f769a9824F15E6Ce58591Da4781;

  // https://etherscan.io/address/0x2D9fe18b6c35FE439cC15D932cc5C943bf2d901E
  address internal constant USDS_V_TOKEN = 0x2D9fe18b6c35FE439cC15D932cc5C943bf2d901E;

  // https://etherscan.io/address/0x94C7FD62fd0506e71d8142E9D36687fC72A86B02
  address internal constant USDS_ORACLE = 0x94C7FD62fd0506e71d8142E9D36687fC72A86B02;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant USDS_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
  address internal constant USDC_UNDERLYING = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://etherscan.io/address/0x2A1FBcb52Ed4d9b23daD17E1E8Aed4BB0E6079b8
  address internal constant USDC_A_TOKEN = 0x2A1FBcb52Ed4d9b23daD17E1E8Aed4BB0E6079b8;

  // https://etherscan.io/address/0xeD90dE2D824Ee766c6Fd22E90b12e598f681dc9F
  address internal constant USDC_V_TOKEN = 0xeD90dE2D824Ee766c6Fd22E90b12e598f681dc9F;

  // https://etherscan.io/address/0x3f73F03aa83B2A48ed27E964eD0fDb590332095B
  address internal constant USDC_ORACLE = 0x3f73F03aa83B2A48ed27E964eD0fDb590332095B;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0xbf5495Efe5DB9ce00f80364C8B423567e58d2110
  address internal constant ezETH_UNDERLYING = 0xbf5495Efe5DB9ce00f80364C8B423567e58d2110;

  uint8 internal constant ezETH_DECIMALS = 18;

  // https://etherscan.io/address/0x74e5664394998f13B07aF42446380ACef637969f
  address internal constant ezETH_A_TOKEN = 0x74e5664394998f13B07aF42446380ACef637969f;

  // https://etherscan.io/address/0x08e1bba76D27841dD91FAb4b3a636A0D5CF8c3E9
  address internal constant ezETH_V_TOKEN = 0x08e1bba76D27841dD91FAb4b3a636A0D5CF8c3E9;

  // https://etherscan.io/address/0xF3d49021fF3bbBFDfC1992A4b09E5D1d141D044C
  address internal constant ezETH_ORACLE = 0xF3d49021fF3bbBFDfC1992A4b09E5D1d141D044C;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant ezETH_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0x9D39A5DE30e57443BfF2A8307A4256c8797A3497
  address internal constant sUSDe_UNDERLYING = 0x9D39A5DE30e57443BfF2A8307A4256c8797A3497;

  uint8 internal constant sUSDe_DECIMALS = 18;

  // https://etherscan.io/address/0xc2015641564a5914A17CB9A92eC8d8feCfa8f2D0
  address internal constant sUSDe_A_TOKEN = 0xc2015641564a5914A17CB9A92eC8d8feCfa8f2D0;

  // https://etherscan.io/address/0x2ABbAab3EF4e4A899d39e7EC996b5715E76b399a
  address internal constant sUSDe_V_TOKEN = 0x2ABbAab3EF4e4A899d39e7EC996b5715E76b399a;

  // https://etherscan.io/address/0x42bc86f2f08419280a99d8fbEa4672e7c30a86ec
  address internal constant sUSDe_ORACLE = 0x42bc86f2f08419280a99d8fbEa4672e7c30a86ec;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant sUSDe_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f
  address internal constant GHO_UNDERLYING = 0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f;

  uint8 internal constant GHO_DECIMALS = 18;

  // https://etherscan.io/address/0x18eFE565A5373f430e2F809b97De30335B3ad96A
  address internal constant GHO_A_TOKEN = 0x18eFE565A5373f430e2F809b97De30335B3ad96A;

  // https://etherscan.io/address/0x18577F0f4A0B2Ee6F4048dB51c7acd8699F97DB8
  address internal constant GHO_V_TOKEN = 0x18577F0f4A0B2Ee6F4048dB51c7acd8699F97DB8;

  // https://etherscan.io/address/0xD110cac5d8682A3b045D5524a9903E031d70FCCd
  address internal constant GHO_ORACLE = 0xD110cac5d8682A3b045D5524a9903E031d70FCCd;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant GHO_INTEREST_RATE_STRATEGY = 0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0xC71Ea051a5F82c67ADcF634c36FFE6334793D24C
  address internal constant GHO_STATA_TOKEN = 0xC71Ea051a5F82c67ADcF634c36FFE6334793D24C;

  // https://etherscan.io/address/0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7
  address internal constant rsETH_UNDERLYING = 0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7;

  uint8 internal constant rsETH_DECIMALS = 18;

  // https://etherscan.io/address/0x56D919E7B25aA42F3F8a4BC77b8982048F2E84B4
  address internal constant rsETH_A_TOKEN = 0x56D919E7B25aA42F3F8a4BC77b8982048F2E84B4;

  // https://etherscan.io/address/0x2c2163f120cf58631368981BC16e90190Bc6C644
  address internal constant rsETH_V_TOKEN = 0x2c2163f120cf58631368981BC16e90190Bc6C644;

  // https://etherscan.io/address/0x7292C95A5f6A501a9c4B34f6393e221F2A0139c3
  address internal constant rsETH_ORACLE = 0x7292C95A5f6A501a9c4B34f6393e221F2A0139c3;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant rsETH_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;

  // https://etherscan.io/address/0xD11c452fc99cF405034ee446803b6F6c1F6d5ED8
  address internal constant tETH_UNDERLYING = 0xD11c452fc99cF405034ee446803b6F6c1F6d5ED8;

  uint8 internal constant tETH_DECIMALS = 18;

  // https://etherscan.io/address/0xce8c60fd8390eFCc3Fc66A3f0bd64BEb969e750E
  address internal constant tETH_A_TOKEN = 0xce8c60fd8390eFCc3Fc66A3f0bd64BEb969e750E;

  // https://etherscan.io/address/0xe7ea6125490ae4594aD9B44D05dFF9F2A4343134
  address internal constant tETH_V_TOKEN = 0xe7ea6125490ae4594aD9B44D05dFF9F2A4343134;

  // https://etherscan.io/address/0x85968026294b8f8Fb86d6bF3Cda079f9376aD05A
  address internal constant tETH_ORACLE = 0x85968026294b8f8Fb86d6bF3Cda079f9376aD05A;

  // https://etherscan.io/address/0x8958b1C39269167527821f8c276Ef7504883f2fa
  address internal constant tETH_INTEREST_RATE_STRATEGY =
    0x8958b1C39269167527821f8c276Ef7504883f2fa;
}
library AaveV3EthereumLidoEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant WSTETH_WETH = 1;

  uint8 internal constant LRT_STABLECOINS_MAIN = 2;

  uint8 internal constant LRT_WSTETH_MAIN = 3;

  uint8 internal constant SUSDE_STABLECOINS = 4;

  uint8 internal constant RSETH_LST_MAIN = 5;

  uint8 internal constant RSETH_STABLECOINS = 6;

  uint8 internal constant TETH_WSTETH = 7;
}
library AaveV3EthereumLidoExternalLibraries {
  // https://etherscan.io/address/0x5e84CEe2afb7B37d2AB14722C39A7c1C26F5B0BB
  address internal constant FLASHLOAN_LOGIC = 0x5e84CEe2afb7B37d2AB14722C39A7c1C26F5B0BB;

  // https://etherscan.io/address/0xFeD9871528E713B5038c4c44BbE7a315f56cAdc6
  address internal constant BORROW_LOGIC = 0xFeD9871528E713B5038c4c44BbE7a315f56cAdc6;

  // https://etherscan.io/address/0xD1bddC05A3BB5A7907d82A1b4F1E21dBCE69c3d5
  address internal constant E_MODE_LOGIC = 0xD1bddC05A3BB5A7907d82A1b4F1E21dBCE69c3d5;

  // https://etherscan.io/address/0x36Ae486289bB807C3C79A1427b9c3D934294ef43
  address internal constant LIQUIDATION_LOGIC = 0x36Ae486289bB807C3C79A1427b9c3D934294ef43;

  // https://etherscan.io/address/0xE51B69e5722Bf547866A4d7Bc190c6e81b626806
  address internal constant POOL_LOGIC = 0xE51B69e5722Bf547866A4d7Bc190c6e81b626806;

  // https://etherscan.io/address/0x034Fd14b9Ae6bB066a1F9f85A55e990b0b25c168
  address internal constant SUPPLY_LOGIC = 0x034Fd14b9Ae6bB066a1F9f85A55e990b0b25c168;
}
