// SPDX-License-Identifier: MIT
// AUTOGENERATED - DON'T MANUALLY CHANGE
pragma solidity >=0.6.0;

library AaveV2AvalancheAssets {
  address internal constant UNDERLYING_WETHe = 0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB;

  address internal constant A_TOKEN_WETHe = 0x53f7c5869a859F0AeC3D334ee8B4Cf01E3492f21;

  address internal constant V_TOKEN_WETHe = 0x4e575CacB37bc1b5afEc68a0462c4165A5268983;

  address internal constant S_TOKEN_WETHe = 0x60F6A45006323B97d97cB0a42ac39e2b757ADA63;

  address internal constant ORACLE_WETHe = 0x976B3D034E162d8bD72D6b9C989d545b839003b0;

  address internal constant INTEREST_RATE_STRATEGY_WETHe =
    0x6724e923E4bb58fCdF7CEe7A5E7bBb47b99C2647;

  address internal constant UNDERLYING_DAIe = 0xd586E7F844cEa2F87f50152665BCbc2C279D8d70;

  address internal constant A_TOKEN_DAIe = 0x47AFa96Cdc9fAb46904A55a6ad4bf6660B53c38a;

  address internal constant V_TOKEN_DAIe = 0x1852DC24d1a8956a0B356AA18eDe954c7a0Ca5ae;

  address internal constant S_TOKEN_DAIe = 0x3676E4EE689D527dDb89812B63fAD0B7501772B3;

  address internal constant ORACLE_DAIe = 0x51D7180edA2260cc4F6e4EebB82FEF5c3c2B8300;

  address internal constant INTEREST_RATE_STRATEGY_DAIe =
    0xD96B68638bdbb625A49F5BAC0dC3B66764569d30;

  address internal constant UNDERLYING_USDTe = 0xc7198437980c041c805A1EDcbA50c1Ce5db95118;

  address internal constant A_TOKEN_USDTe = 0x532E6537FEA298397212F09A61e03311686f548e;

  address internal constant V_TOKEN_USDTe = 0xfc1AdA7A288d6fCe0d29CcfAAa57Bc9114bb2DbE;

  address internal constant S_TOKEN_USDTe = 0x9c7B81A867499B7387ed05017a13d4172a0c17bF;

  address internal constant ORACLE_USDTe = 0xEBE676ee90Fe1112671f19b6B7459bC678B67e8a;

  address internal constant INTEREST_RATE_STRATEGY_USDTe =
    0xD96B68638bdbb625A49F5BAC0dC3B66764569d30;

  address internal constant UNDERLYING_USDCe = 0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664;

  address internal constant A_TOKEN_USDCe = 0x46A51127C3ce23fb7AB1DE06226147F446e4a857;

  address internal constant V_TOKEN_USDCe = 0x848c080d2700CBE1B894a3374AD5E887E5cCb89c;

  address internal constant S_TOKEN_USDCe = 0x5B14679135dbE8B02015ec3Ca4924a12E4C6C85a;

  address internal constant ORACLE_USDCe = 0xF096872672F44d6EBA71458D74fe67F9a77a23B9;

  address internal constant INTEREST_RATE_STRATEGY_USDCe =
    0xD96B68638bdbb625A49F5BAC0dC3B66764569d30;

  address internal constant UNDERLYING_AAVEe = 0x63a72806098Bd3D9520cC43356dD78afe5D386D9;

  address internal constant A_TOKEN_AAVEe = 0xD45B7c061016102f9FA220502908f2c0f1add1D7;

  address internal constant V_TOKEN_AAVEe = 0x8352E3fd18B8d84D3c8a1b538d788899073c7A8E;

  address internal constant S_TOKEN_AAVEe = 0x66904E4F3f44e3925D22ceca401b6F2DA085c98f;

  address internal constant ORACLE_AAVEe = 0x3CA13391E9fb38a75330fb28f8cc2eB3D9ceceED;

  address internal constant INTEREST_RATE_STRATEGY_AAVEe =
    0x6724e923E4bb58fCdF7CEe7A5E7bBb47b99C2647;

  address internal constant UNDERLYING_WBTCe = 0x50b7545627a5162F82A992c33b87aDc75187B218;

  address internal constant A_TOKEN_WBTCe = 0x686bEF2417b6Dc32C50a3cBfbCC3bb60E1e9a15D;

  address internal constant V_TOKEN_WBTCe = 0x2dc0E35eC3Ab070B8a175C829e23650Ee604a9eB;

  address internal constant S_TOKEN_WBTCe = 0x3484408989985d68C9700dc1CFDFeAe6d2f658CF;

  address internal constant ORACLE_WBTCe = 0x2779D32d5166BAaa2B2b658333bA7e6Ec0C65743;

  address internal constant INTEREST_RATE_STRATEGY_WBTCe =
    0x6724e923E4bb58fCdF7CEe7A5E7bBb47b99C2647;

  address internal constant UNDERLYING_WAVAX = 0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7;

  address internal constant A_TOKEN_WAVAX = 0xDFE521292EcE2A4f44242efBcD66Bc594CA9714B;

  address internal constant V_TOKEN_WAVAX = 0x66A0FE52Fb629a6cB4D10B8580AFDffE888F5Fd4;

  address internal constant S_TOKEN_WAVAX = 0x2920CD5b8A160b2Addb00Ec5d5f4112255d4ae75;

  address internal constant ORACLE_WAVAX = 0x0A77230d17318075983913bC2145DB16C7366156;

  address internal constant INTEREST_RATE_STRATEGY_WAVAX =
    0x6724e923E4bb58fCdF7CEe7A5E7bBb47b99C2647;
}
