// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3Mantle {
  // https://mantlescan.xyz/address/0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f);

  // https://mantlescan.xyz/address/0x458F293454fE0d67EC0655f3672301301DD51422
  IPool internal constant POOL = IPool(0x458F293454fE0d67EC0655f3672301301DD51422);

  // https://mantlescan.xyz/address/0x719755fC1ACf2f9079B0Cbc56e23712c09Ab8626
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x719755fC1ACf2f9079B0Cbc56e23712c09Ab8626);

  // https://mantlescan.xyz/address/0x47a063CfDa980532267970d478EC340C0F80E8df
  IAaveOracle internal constant ORACLE = IAaveOracle(0x47a063CfDa980532267970d478EC340C0F80E8df);

  // https://mantlescan.xyz/address/0x64df9D4302e1ff3516Dc744A19e992D27CAC252E
  address internal constant PRICE_ORACLE_SENTINEL = 0x64df9D4302e1ff3516Dc744A19e992D27CAC252E;

  // https://mantlescan.xyz/address/0x70884634D0098782592111A2A6B8d223be31CB7b
  address internal constant ACL_ADMIN = 0x70884634D0098782592111A2A6B8d223be31CB7b;

  // https://mantlescan.xyz/address/0x810D46F9a9027E28F9B01F75E2bdde839dA61115
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x810D46F9a9027E28F9B01F75E2bdde839dA61115);

  // https://mantlescan.xyz/address/0x487c5c669D9eee6057C44973207101276cf73b68
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x487c5c669D9eee6057C44973207101276cf73b68);

  // https://mantlescan.xyz/address/0x822639a811cD85c799c77Eb3502617e6Ea27486E
  address internal constant POOL_IMPL = 0x822639a811cD85c799c77Eb3502617e6Ea27486E;

  // https://mantlescan.xyz/address/0xAe5A1e33E6ef3119e9EC92dD26865eef280e145A
  address internal constant POOL_CONFIGURATOR_IMPL = 0xAe5A1e33E6ef3119e9EC92dD26865eef280e145A;

  // https://mantlescan.xyz/address/0x682482a584eE20fefc01f4575c45C5d84de6F619
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x682482a584eE20fefc01f4575c45C5d84de6F619;

  // https://mantlescan.xyz/address/0x67eD9aC2b65F2ACa57ef2B6BA709251BC2B5036d
  address internal constant EMISSION_MANAGER = 0x67eD9aC2b65F2ACa57ef2B6BA709251BC2B5036d;

  // https://mantlescan.xyz/address/0x0cd2670339Cd520BF9428Ad881bE60A698aB9B32
  ICollector internal constant COLLECTOR = ICollector(0x0cd2670339Cd520BF9428Ad881bE60A698aB9B32);

  // https://mantlescan.xyz/address/0xD7ab0676222c0235e09a06640c422bf97CCC2Bc5
  address internal constant DEFAULT_A_TOKEN_IMPL = 0xD7ab0676222c0235e09a06640c422bf97CCC2Bc5;

  // https://mantlescan.xyz/address/0x604174a3bA9228F3c7823d2E1aAA17A90E06C160
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0x604174a3bA9228F3c7823d2E1aAA17A90E06C160;

  // https://mantlescan.xyz/address/0x70Bf6EC6Fca41a7d08dCBB9909985AC0A4510B5E
  address internal constant CONFIG_ENGINE = 0x70Bf6EC6Fca41a7d08dCBB9909985AC0A4510B5E;

  // https://mantlescan.xyz/address/0x54114591963CF60EF3aA63bEfD6eC263D98145a4
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0x54114591963CF60EF3aA63bEfD6eC263D98145a4;

  // https://mantlescan.xyz/address/0x04EEC4892Ec41A056C66787211aE81A24460fF02
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x04EEC4892Ec41A056C66787211aE81A24460fF02;

  // https://mantlescan.xyz/address/0x077df1990bF703fb1687515747ddb13621133649
  address internal constant UI_POOL_DATA_PROVIDER = 0x077df1990bF703fb1687515747ddb13621133649;

  // https://mantlescan.xyz/address/0x91855bbfE5F19c245C3dA9B9fC954394a6f9da8f
  address internal constant WALLET_BALANCE_PROVIDER = 0x91855bbfE5F19c245C3dA9B9fC954394a6f9da8f;

  // https://mantlescan.xyz/address/0x9C6cCAC66b1c9AbA4855e2dD284b9e16e41E06eA
  address internal constant WETH_GATEWAY = 0x9C6cCAC66b1c9AbA4855e2dD284b9e16e41E06eA;

  // https://mantlescan.xyz/address/0x1F25c3f23D05984DBA88EC59F2109fC4F29833eA
  address internal constant L2_ENCODER = 0x1F25c3f23D05984DBA88EC59F2109fC4F29833eA;

  // https://mantlescan.xyz/address/0xfd4Eb6c531A34EC3A74C99892C5511fe6d126F91
  address internal constant STATA_FACTORY = 0xfd4Eb6c531A34EC3A74C99892C5511fe6d126F91;

  // https://mantlescan.xyz/address/0xa35358159F42E11C5689C68f181a71d51BB22de3
  address internal constant RISK_STEWARD = 0xa35358159F42E11C5689C68f181a71d51BB22de3;

  // https://mantlescan.xyz/address/0xB238ce4d8EA3D99b0d90Fe7DA3F17149F88a2601
  address internal constant DUST_BIN = 0xB238ce4d8EA3D99b0d90Fe7DA3F17149F88a2601;
}
library AaveV3MantleAssets {
  // https://mantlescan.xyz/address/0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111
  address internal constant WETH_UNDERLYING = 0xdEAddEaDdeadDEadDEADDEAddEADDEAddead1111;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://mantlescan.xyz/address/0xeAC30Ed8609F564aE65C809C4bf42dB2fF426D2C
  address internal constant WETH_A_TOKEN = 0xeAC30Ed8609F564aE65C809C4bf42dB2fF426D2C;

  // https://mantlescan.xyz/address/0x0baF5974838114e7001D02782e6B1D8aEE1fc626
  address internal constant WETH_V_TOKEN = 0x0baF5974838114e7001D02782e6B1D8aEE1fc626;

  // https://mantlescan.xyz/address/0x5bc7Cf88EB131DB18b5d7930e793095140799aD5
  address internal constant WETH_ORACLE = 0x5bc7Cf88EB131DB18b5d7930e793095140799aD5;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x78c1b0C915c4FAA5FffA6CAbf0219DA63d7f4cb8
  address internal constant WMNT_UNDERLYING = 0x78c1b0C915c4FAA5FffA6CAbf0219DA63d7f4cb8;

  uint8 internal constant WMNT_DECIMALS = 18;

  // https://mantlescan.xyz/address/0x85d86061e94CE01D3DA0f9EFa289c86ff136125a
  address internal constant WMNT_A_TOKEN = 0x85d86061e94CE01D3DA0f9EFa289c86ff136125a;

  // https://mantlescan.xyz/address/0x9c27A8ffacAbdEE0Ac5c415E018D295BB6444F0E
  address internal constant WMNT_V_TOKEN = 0x9c27A8ffacAbdEE0Ac5c415E018D295BB6444F0E;

  // https://mantlescan.xyz/address/0xD97F20bEbeD74e8144134C4b148fE93417dd0F96
  address internal constant WMNT_ORACLE = 0xD97F20bEbeD74e8144134C4b148fE93417dd0F96;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant WMNT_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x779Ded0c9e1022225f8E0630b35a9b54bE713736
  address internal constant USDT0_UNDERLYING = 0x779Ded0c9e1022225f8E0630b35a9b54bE713736;

  uint8 internal constant USDT0_DECIMALS = 6;

  // https://mantlescan.xyz/address/0x7053bAD224F0C021839f6AC645BdaE5F8b585b69
  address internal constant USDT0_A_TOKEN = 0x7053bAD224F0C021839f6AC645BdaE5F8b585b69;

  // https://mantlescan.xyz/address/0x5d9e4663d3d532179c404dBe9edF93045F89aDed
  address internal constant USDT0_V_TOKEN = 0x5d9e4663d3d532179c404dBe9edF93045F89aDed;

  // https://mantlescan.xyz/address/0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee
  address internal constant USDT0_ORACLE = 0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant USDT0_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x09Bc4E0D864854c6aFB6eB9A9cdF58aC190D0dF9
  address internal constant USDC_UNDERLYING = 0x09Bc4E0D864854c6aFB6eB9A9cdF58aC190D0dF9;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://mantlescan.xyz/address/0xcb8164415274515867ec43CbD284ab5d6d2b304F
  address internal constant USDC_A_TOKEN = 0xcb8164415274515867ec43CbD284ab5d6d2b304F;

  // https://mantlescan.xyz/address/0xCea474BDa7Ad0a8F62e938a5563edfAEf7368Fc0
  address internal constant USDC_V_TOKEN = 0xCea474BDa7Ad0a8F62e938a5563edfAEf7368Fc0;

  // https://mantlescan.xyz/address/0x3876FB349c14613e0633b5cAe08C4E3B1d4904fB
  address internal constant USDC_ORACLE = 0x3876FB349c14613e0633b5cAe08C4E3B1d4904fB;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34
  address internal constant USDe_UNDERLYING = 0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34;

  uint8 internal constant USDe_DECIMALS = 18;

  // https://mantlescan.xyz/address/0xb9aCA933C9c0aa854a6DBb7b12f0CC3FdaC15ee7
  address internal constant USDe_A_TOKEN = 0xb9aCA933C9c0aa854a6DBb7b12f0CC3FdaC15ee7;

  // https://mantlescan.xyz/address/0x0169FD279c8c656037E5D199Cff8137f1e2d807c
  address internal constant USDe_V_TOKEN = 0x0169FD279c8c656037E5D199Cff8137f1e2d807c;

  // https://mantlescan.xyz/address/0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee
  address internal constant USDe_ORACLE = 0xFA5dEcEd7cdCEAB065addd0E32D9527ABd1069Ee;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant USDe_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2
  address internal constant sUSDe_UNDERLYING = 0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2;

  uint8 internal constant sUSDe_DECIMALS = 18;

  // https://mantlescan.xyz/address/0xaf972F332FF79bd32A6CB6B54f903eA0F9b16C2a
  address internal constant sUSDe_A_TOKEN = 0xaf972F332FF79bd32A6CB6B54f903eA0F9b16C2a;

  // https://mantlescan.xyz/address/0xc42B44c65bBe7AA8E5b02416918688c244ec7847
  address internal constant sUSDe_V_TOKEN = 0xc42B44c65bBe7AA8E5b02416918688c244ec7847;

  // https://mantlescan.xyz/address/0x8b47EC48ac560793861D94A997d020872c1cE3f5
  address internal constant sUSDe_ORACLE = 0x8b47EC48ac560793861D94A997d020872c1cE3f5;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant sUSDe_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0xC96dE26018A54D51c097160568752c4E3BD6C364
  address internal constant FBTC_UNDERLYING = 0xC96dE26018A54D51c097160568752c4E3BD6C364;

  uint8 internal constant FBTC_DECIMALS = 8;

  // https://mantlescan.xyz/address/0xfa14c9DE267b59A586043372bd98Ed99e3Ee0533
  address internal constant FBTC_A_TOKEN = 0xfa14c9DE267b59A586043372bd98Ed99e3Ee0533;

  // https://mantlescan.xyz/address/0x691AbCD512C1Cfef99442b0ACD3eD98Ee7F4e64E
  address internal constant FBTC_V_TOKEN = 0x691AbCD512C1Cfef99442b0ACD3eD98Ee7F4e64E;

  // https://mantlescan.xyz/address/0x7db2275279F52D0914A481e14c4Ce5a59705A25b
  address internal constant FBTC_ORACLE = 0x7db2275279F52D0914A481e14c4Ce5a59705A25b;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant FBTC_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x051665f2455116e929b9972c36d23070F5054Ce0
  address internal constant syrupUSDT_UNDERLYING = 0x051665f2455116e929b9972c36d23070F5054Ce0;

  uint8 internal constant syrupUSDT_DECIMALS = 6;

  // https://mantlescan.xyz/address/0xF8400F3FA9cD9F9E84e93cD9De9f14EB7B5b59b5
  address internal constant syrupUSDT_A_TOKEN = 0xF8400F3FA9cD9F9E84e93cD9De9f14EB7B5b59b5;

  // https://mantlescan.xyz/address/0x2E20c5291CD675bFe52a533a6208588f5484999e
  address internal constant syrupUSDT_V_TOKEN = 0x2E20c5291CD675bFe52a533a6208588f5484999e;

  // https://mantlescan.xyz/address/0xCF1700Ee060AB65fa16d5f44A6fBf16721EB0D9b
  address internal constant syrupUSDT_ORACLE = 0xCF1700Ee060AB65fa16d5f44A6fBf16721EB0D9b;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant syrupUSDT_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0x93e855643e940D025bE2e529272e4Dbd15a2Cf74
  address internal constant wrsETH_UNDERLYING = 0x93e855643e940D025bE2e529272e4Dbd15a2Cf74;

  uint8 internal constant wrsETH_DECIMALS = 18;

  // https://mantlescan.xyz/address/0x5cC6999aC46F4627309a7ce0F321a3f45D138ED5
  address internal constant wrsETH_A_TOKEN = 0x5cC6999aC46F4627309a7ce0F321a3f45D138ED5;

  // https://mantlescan.xyz/address/0x7C5549DE0dEb930bAb1e11B075151a19e400605c
  address internal constant wrsETH_V_TOKEN = 0x7C5549DE0dEb930bAb1e11B075151a19e400605c;

  // https://mantlescan.xyz/address/0xFED794060D37391d966F931B9509378063C5B0fB
  address internal constant wrsETH_ORACLE = 0xFED794060D37391d966F931B9509378063C5B0fB;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant wrsETH_INTEREST_RATE_STRATEGY =
    0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;

  // https://mantlescan.xyz/address/0xfc421aD3C883Bf9E7C4f42dE845C4e4405799e73
  address internal constant GHO_UNDERLYING = 0xfc421aD3C883Bf9E7C4f42dE845C4e4405799e73;

  uint8 internal constant GHO_DECIMALS = 18;

  // https://mantlescan.xyz/address/0x8917d4eE4609f991b559DAF8D0aD1b892c13B127
  address internal constant GHO_A_TOKEN = 0x8917d4eE4609f991b559DAF8D0aD1b892c13B127;

  // https://mantlescan.xyz/address/0xeE1eABe23fA42028809F587B8fE1936b154d2620
  address internal constant GHO_V_TOKEN = 0xeE1eABe23fA42028809F587B8fE1936b154d2620;

  // https://mantlescan.xyz/address/0x360d8aa8F6b09B7BC57aF34db2Eb84dD87bf4d12
  address internal constant GHO_ORACLE = 0x360d8aa8F6b09B7BC57aF34db2Eb84dD87bf4d12;

  // https://mantlescan.xyz/address/0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a
  address internal constant GHO_INTEREST_RATE_STRATEGY = 0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a;
}
library AaveV3MantleEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant USDe_sUSDe__USDT0_USDC_GHO = 1;

  uint8 internal constant USDe__USDT0_USDC_GHO = 2;

  uint8 internal constant FBTC__USDT0_USDC_USDe = 3;

  uint8 internal constant syrupUSDT__USDT0_USDC_GHO = 4;

  uint8 internal constant wrsETH__WETH = 5;
}
library AaveV3MantleExternalLibraries {
  // https://mantlescan.xyz/address/0x8e7aadB7bBAb02Ad899A13FF9A75571A4866Bf04
  address internal constant FLASHLOAN_LOGIC = 0x8e7aadB7bBAb02Ad899A13FF9A75571A4866Bf04;

  // https://mantlescan.xyz/address/0x1Fb8f7C906cddD28B42ae6Eb76abC04A91188635
  address internal constant BORROW_LOGIC = 0x1Fb8f7C906cddD28B42ae6Eb76abC04A91188635;

  // https://mantlescan.xyz/address/0x8dc095F287dBEBD9e15f75BB3DfBF18389BB8104
  address internal constant LIQUIDATION_LOGIC = 0x8dc095F287dBEBD9e15f75BB3DfBF18389BB8104;

  // https://mantlescan.xyz/address/0x25Ed699a052B820d772765E26Ed4dD9f0A26F3E5
  address internal constant POOL_LOGIC = 0x25Ed699a052B820d772765E26Ed4dD9f0A26F3E5;

  // https://mantlescan.xyz/address/0x33654b16A4De97bCE05d7dD06803Bf1066f3123C
  address internal constant SUPPLY_LOGIC = 0x33654b16A4De97bCE05d7dD06803Bf1066f3123C;
}
