// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3Sonic {
  // https://sonicscan.org/address/0x5C2e738F6E27bCE0F7558051Bf90605dD6176900
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x5C2e738F6E27bCE0F7558051Bf90605dD6176900);

  // https://sonicscan.org/address/0x5362dBb1e601abF3a4c14c22ffEdA64042E5eAA3
  IPool internal constant POOL = IPool(0x5362dBb1e601abF3a4c14c22ffEdA64042E5eAA3);

  // https://sonicscan.org/address/0x50c70FEB95aBC1A92FC30b9aCc41Bd349E5dE2f0
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x50c70FEB95aBC1A92FC30b9aCc41Bd349E5dE2f0);

  // https://sonicscan.org/address/0xD63f7658C66B2934Bd234D79D06aEF5290734B30
  IAaveOracle internal constant ORACLE = IAaveOracle(0xD63f7658C66B2934Bd234D79D06aEF5290734B30);

  // https://sonicscan.org/address/0x7b62461a3570c6AC8a9f8330421576e417B71EE7
  address internal constant ACL_ADMIN = 0x7b62461a3570c6AC8a9f8330421576e417B71EE7;

  // https://sonicscan.org/address/0x3a790a47c4d531FD333FAD24f70B0ccb521B3b5A
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x3a790a47c4d531FD333FAD24f70B0ccb521B3b5A);

  // https://sonicscan.org/address/0xc0a344397cfa89dF1e1d3e4fb330834D789cF2CD
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xc0a344397cfa89dF1e1d3e4fb330834D789cF2CD);

  // https://sonicscan.org/address/0x3023FE480Df7365FcC12ADc04779f4ca9b13f1b5
  address internal constant POOL_IMPL = 0x3023FE480Df7365FcC12ADc04779f4ca9b13f1b5;

  // https://sonicscan.org/address/0x5793FE4de34532F162B4e207aF872729880ec2b6
  address internal constant POOL_CONFIGURATOR_IMPL = 0x5793FE4de34532F162B4e207aF872729880ec2b6;

  // https://sonicscan.org/address/0x24bD6e9ca54F1737467DEf82dCA9702925B3Aa59
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x24bD6e9ca54F1737467DEf82dCA9702925B3Aa59;

  // https://sonicscan.org/address/0xd3A0A19Cdb7d1615f30988763BEA5f8feCc17a87
  address internal constant EMISSION_MANAGER = 0xd3A0A19Cdb7d1615f30988763BEA5f8feCc17a87;

  // https://sonicscan.org/address/0x1aB55bBdD5DF0782BBCf73553Af93BC6B29A286B
  ICollector internal constant COLLECTOR = ICollector(0x1aB55bBdD5DF0782BBCf73553Af93BC6B29A286B);

  // https://sonicscan.org/address/0x4e7ec41282A295e722F13d32C025f03358F72C92
  address internal constant DEFAULT_A_TOKEN_IMPL = 0x4e7ec41282A295e722F13d32C025f03358F72C92;

  // https://sonicscan.org/address/0xc47692016D70496E2E44531AAa8511aa07D4D185
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0xc47692016D70496E2E44531AAa8511aa07D4D185;

  // https://sonicscan.org/address/0xDa98B308be8766501ec7Fe3eD9a48EfBD6c31a7B
  address internal constant CONFIG_ENGINE = 0xDa98B308be8766501ec7Fe3eD9a48EfBD6c31a7B;

  // https://sonicscan.org/address/0xdb93e2712a8B36835078f8D28c70fCC95FD6d37c
  address internal constant RISK_STEWARD = 0xdb93e2712a8B36835078f8D28c70fCC95FD6d37c;

  // https://sonicscan.org/address/0x5E5D87858592d211fdb4503F09FB2B5cf805cB51
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0x5E5D87858592d211fdb4503F09FB2B5cf805cB51;

  // https://sonicscan.org/address/0xeC859AED64e87004FA724892D5aB474901825B2D
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xeC859AED64e87004FA724892D5aB474901825B2D;

  // https://sonicscan.org/address/0x9005A69fE088680827f292e8aE885Be4BE1beb2f
  address internal constant UI_POOL_DATA_PROVIDER = 0x9005A69fE088680827f292e8aE885Be4BE1beb2f;

  // https://sonicscan.org/address/0x6637Ef9c6b41Fa62d69b7E88C5Dd9eF30BbEE945
  address internal constant WALLET_BALANCE_PROVIDER = 0x6637Ef9c6b41Fa62d69b7E88C5Dd9eF30BbEE945;

  // https://sonicscan.org/address/0x061D8e131F26512348ee5FA42e2DF1bA9d6505E9
  address internal constant WETH_GATEWAY = 0x061D8e131F26512348ee5FA42e2DF1bA9d6505E9;

  // https://sonicscan.org/address/0xFeeb6FE430B7523fEF2a38327241eE7153779535
  address internal constant STATA_FACTORY = 0xFeeb6FE430B7523fEF2a38327241eE7153779535;

  // https://sonicscan.org/address/0x62aDD9C6B511085C67515ebB799b51c4cf2d786F
  address internal constant DUST_BIN = 0x62aDD9C6B511085C67515ebB799b51c4cf2d786F;

  // https://sonicscan.org/address/0x4A137d528444Cc0346320CFa5C80FFc68087D7F9
  address internal constant POOL_EXPOSURE_STEWARD = 0x4A137d528444Cc0346320CFa5C80FFc68087D7F9;

  // https://sonicscan.org/address/0x5598BbFA2f4fE8151f45bBA0a3edE1b54B51a0a9
  address internal constant REPAY_WITH_COLLATERAL_ADAPTER =
    0x5598BbFA2f4fE8151f45bBA0a3edE1b54B51a0a9;

  // https://sonicscan.org/address/0x78F8Bd884C3D738B74B420540659c82f392820e0
  address internal constant SWAP_COLLATERAL_ADAPTER = 0x78F8Bd884C3D738B74B420540659c82f392820e0;

  // https://sonicscan.org/address/0x2E549104c516b8657A7D888494DfbAbD7C70b464
  address internal constant DEBT_SWAP_ADAPTER = 0x2E549104c516b8657A7D888494DfbAbD7C70b464;

  // https://sonicscan.org/address/0x5d4D4007A4c6336550DdAa2a7c0d5e7972eebd16
  address internal constant WITHDRAW_SWAP_ADAPTER = 0x5d4D4007A4c6336550DdAa2a7c0d5e7972eebd16;
}
library AaveV3SonicAssets {
  // https://sonicscan.org/address/0x50c42dEAcD8Fc9773493ED674b675bE577f2634b
  address internal constant WETH_UNDERLYING = 0x50c42dEAcD8Fc9773493ED674b675bE577f2634b;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://sonicscan.org/address/0xe18Ab82c81E7Eecff32B8A82B1b7d2d23F1EcE96
  address internal constant WETH_A_TOKEN = 0xe18Ab82c81E7Eecff32B8A82B1b7d2d23F1EcE96;

  // https://sonicscan.org/address/0x07B1adFB7d5795Cf21baE8a77Eceb222F2FafBCE
  address internal constant WETH_V_TOKEN = 0x07B1adFB7d5795Cf21baE8a77Eceb222F2FafBCE;

  // https://sonicscan.org/address/0x824364077993847f71293B24ccA8567c00c2de11
  address internal constant WETH_ORACLE = 0x824364077993847f71293B24ccA8567c00c2de11;

  // https://sonicscan.org/address/0xdFf435BCcf782f11187D3a4454d96702eD78e092
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0xdFf435BCcf782f11187D3a4454d96702eD78e092;

  // https://sonicscan.org/address/0xeB5e9B0ae5bb60274786C747A1A2A798c11271E0
  address internal constant WETH_STATA_TOKEN = 0xeB5e9B0ae5bb60274786C747A1A2A798c11271E0;

  // https://sonicscan.org/address/0x29219dd400f2Bf60E5a23d13Be72B486D4038894
  address internal constant USDC_UNDERLYING = 0x29219dd400f2Bf60E5a23d13Be72B486D4038894;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://sonicscan.org/address/0x578Ee1ca3a8E1b54554Da1Bf7C583506C4CD11c6
  address internal constant USDC_A_TOKEN = 0x578Ee1ca3a8E1b54554Da1Bf7C583506C4CD11c6;

  // https://sonicscan.org/address/0x2273caBAd63b7D247A6b107E723c803fc49953A0
  address internal constant USDC_V_TOKEN = 0x2273caBAd63b7D247A6b107E723c803fc49953A0;

  // https://sonicscan.org/address/0x7A8443a2a5D772db7f1E40DeFe32db485108F128
  address internal constant USDC_ORACLE = 0x7A8443a2a5D772db7f1E40DeFe32db485108F128;

  // https://sonicscan.org/address/0xdFf435BCcf782f11187D3a4454d96702eD78e092
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0xdFf435BCcf782f11187D3a4454d96702eD78e092;

  // https://sonicscan.org/address/0x6646248971427B80ce531bdD793e2Eb859347E55
  address internal constant USDC_STATA_TOKEN = 0x6646248971427B80ce531bdD793e2Eb859347E55;

  // https://sonicscan.org/address/0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38
  address internal constant wS_UNDERLYING = 0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38;

  uint8 internal constant wS_DECIMALS = 18;

  // https://sonicscan.org/address/0x6C5E14A212c1C3e4Baf6f871ac9B1a969918c131
  address internal constant wS_A_TOKEN = 0x6C5E14A212c1C3e4Baf6f871ac9B1a969918c131;

  // https://sonicscan.org/address/0xF6089B790Fbf8F4812a79a31CFAbeB00B06BA7BD
  address internal constant wS_V_TOKEN = 0xF6089B790Fbf8F4812a79a31CFAbeB00B06BA7BD;

  // https://sonicscan.org/address/0xc76dFb89fF298145b417d221B2c747d84952e01d
  address internal constant wS_ORACLE = 0xc76dFb89fF298145b417d221B2c747d84952e01d;

  // https://sonicscan.org/address/0xdFf435BCcf782f11187D3a4454d96702eD78e092
  address internal constant wS_INTEREST_RATE_STRATEGY = 0xdFf435BCcf782f11187D3a4454d96702eD78e092;

  // https://sonicscan.org/address/0x18B7B8695165290f2767BC63c36D3dFEa4C0F9bB
  address internal constant wS_STATA_TOKEN = 0x18B7B8695165290f2767BC63c36D3dFEa4C0F9bB;

  // https://sonicscan.org/address/0xE5DA20F15420aD15DE0fa650600aFc998bbE3955
  address internal constant stS_UNDERLYING = 0xE5DA20F15420aD15DE0fa650600aFc998bbE3955;

  uint8 internal constant stS_DECIMALS = 18;

  // https://sonicscan.org/address/0xeAa74D7F42267eB907092AF4Bc700f667EeD0B8B
  address internal constant stS_A_TOKEN = 0xeAa74D7F42267eB907092AF4Bc700f667EeD0B8B;

  // https://sonicscan.org/address/0x333cFdCB6457C409e4f0C88F3806252bEe5fe425
  address internal constant stS_V_TOKEN = 0x333cFdCB6457C409e4f0C88F3806252bEe5fe425;

  // https://sonicscan.org/address/0x5BA5D5213B47DFE020B1F8d6fB54Db3F74F9ea9a
  address internal constant stS_ORACLE = 0x5BA5D5213B47DFE020B1F8d6fB54Db3F74F9ea9a;

  // https://sonicscan.org/address/0xdFf435BCcf782f11187D3a4454d96702eD78e092
  address internal constant stS_INTEREST_RATE_STRATEGY = 0xdFf435BCcf782f11187D3a4454d96702eD78e092;
}
library AaveV3SonicEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STS_WS = 1;
}
library AaveV3SonicExternalLibraries {
  // https://sonicscan.org/address/0x4fDB5d360f946CFD25b14F346f748204c0C6a2F4
  address internal constant FLASHLOAN_LOGIC = 0x4fDB5d360f946CFD25b14F346f748204c0C6a2F4;

  // https://sonicscan.org/address/0x5047AD5e603Ec4a2AB58aaE2321C07D8f4De6a8a
  address internal constant BORROW_LOGIC = 0x5047AD5e603Ec4a2AB58aaE2321C07D8f4De6a8a;

  // https://sonicscan.org/address/0x7fcE69A2bA3e78EeB36798cde2c94C70f3A043af
  address internal constant E_MODE_LOGIC = 0x7fcE69A2bA3e78EeB36798cde2c94C70f3A043af;

  // https://sonicscan.org/address/0x5934b283f7120500253f277CCcF4521528aE34D6
  address internal constant LIQUIDATION_LOGIC = 0x5934b283f7120500253f277CCcF4521528aE34D6;

  // https://sonicscan.org/address/0x564c42578A1b270EaE16c25Da39d901245881d1F
  address internal constant POOL_LOGIC = 0x564c42578A1b270EaE16c25Da39d901245881d1F;

  // https://sonicscan.org/address/0x1eF34B91afC368174F579067D1DB94325cDC7946
  address internal constant SUPPLY_LOGIC = 0x1eF34B91afC368174F579067D1DB94325cDC7946;
}
