// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3Celo {
  // https://celoscan.io/address/0x9F7Cf9417D5251C59fE94fB9147feEe1aAd9Cea5
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x9F7Cf9417D5251C59fE94fB9147feEe1aAd9Cea5);

  // https://celoscan.io/address/0x3E59A31363E2ad014dcbc521c4a0d5757d9f3402
  IPool internal constant POOL = IPool(0x3E59A31363E2ad014dcbc521c4a0d5757d9f3402);

  // https://celoscan.io/address/0x7567E3434CC1BEf724AB595e6072367Ef4914691
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x7567E3434CC1BEf724AB595e6072367Ef4914691);

  // https://celoscan.io/address/0x1e693D088ceFD1E95ba4c4a5F7EeA41a1Ec37e8b
  IAaveOracle internal constant ORACLE = IAaveOracle(0x1e693D088ceFD1E95ba4c4a5F7EeA41a1Ec37e8b);

  // https://celoscan.io/address/0x1dF462e2712496373A347f8ad10802a5E95f053D
  address internal constant ACL_ADMIN = 0x1dF462e2712496373A347f8ad10802a5E95f053D;

  // https://celoscan.io/address/0x7a12dCfd73C1B4cddf294da4cFce75FcaBBa314C
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x7a12dCfd73C1B4cddf294da4cFce75FcaBBa314C);

  // https://celoscan.io/address/0x2e0f8D3B1631296cC7c56538D6Eb6032601E15ED
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x2e0f8D3B1631296cC7c56538D6Eb6032601E15ED);

  // https://celoscan.io/address/0x62572b5F1428aa9C85Ec2f687FeC7DA614e1baa4
  address internal constant POOL_IMPL = 0x62572b5F1428aa9C85Ec2f687FeC7DA614e1baa4;

  // https://celoscan.io/address/0x5793FE4de34532F162B4e207aF872729880ec2b6
  address internal constant POOL_CONFIGURATOR_IMPL = 0x5793FE4de34532F162B4e207aF872729880ec2b6;

  // https://celoscan.io/address/0x4725A0FdbEB14A77964bC1C221eE3a7982263103
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x4725A0FdbEB14A77964bC1C221eE3a7982263103;

  // https://celoscan.io/address/0x9e04Cb339163b06068397d9b6af2dA78440954e0
  address internal constant EMISSION_MANAGER = 0x9e04Cb339163b06068397d9b6af2dA78440954e0;

  // https://celoscan.io/address/0xC959439207dA5341B74aDcdAC59016aa9Be7E9E7
  ICollector internal constant COLLECTOR = ICollector(0xC959439207dA5341B74aDcdAC59016aa9Be7E9E7);

  // https://celoscan.io/address/0x0B89E33cDe70fa6fd2cD1C243790B9e19a914927
  address internal constant DEFAULT_A_TOKEN_IMPL = 0x0B89E33cDe70fa6fd2cD1C243790B9e19a914927;

  // https://celoscan.io/address/0x63E00463fDD1f3308C452a38D21834c6cED83836
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0x63E00463fDD1f3308C452a38D21834c6cED83836;

  // https://celoscan.io/address/0x6BC59F65bdA1bE5c2936cAA36081A652c01C7BFb
  address internal constant CONFIG_ENGINE = 0x6BC59F65bdA1bE5c2936cAA36081A652c01C7BFb;

  // https://celoscan.io/address/0xB4B6939D0804DCE8d0Ac3e59b2eD5C072829d56b
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0xB4B6939D0804DCE8d0Ac3e59b2eD5C072829d56b;

  // https://celoscan.io/address/0x3A1Ea5fB3098b9767E0e85D63E28A5c0EAa44099
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x3A1Ea5fB3098b9767E0e85D63E28A5c0EAa44099;

  // https://celoscan.io/address/0xf07fFd12b119b921C4a2ce8d4A13C5d1E3000d6e
  address internal constant UI_POOL_DATA_PROVIDER = 0xf07fFd12b119b921C4a2ce8d4A13C5d1E3000d6e;

  // https://celoscan.io/address/0xB91DA65093d54a1a7cb0fe684860F568A5E57123
  address internal constant WALLET_BALANCE_PROVIDER = 0xB91DA65093d54a1a7cb0fe684860F568A5E57123;

  // https://celoscan.io/address/0x2b33073B94243304bCb4dfFA6b624afA5BAA414D
  address internal constant STATA_FACTORY = 0x2b33073B94243304bCb4dfFA6b624afA5BAA414D;

  // https://celoscan.io/address/0xdb93e2712a8B36835078f8D28c70fCC95FD6d37c
  address internal constant RISK_STEWARD = 0xdb93e2712a8B36835078f8D28c70fCC95FD6d37c;

  // https://celoscan.io/address/0x886b90e5d7DA22000f1652740D3EC51566AAbe40
  address internal constant DUST_BIN = 0x886b90e5d7DA22000f1652740D3EC51566AAbe40;
}
library AaveV3CeloAssets {
  // https://celoscan.io/address/0xcebA9300f2b948710d2653dD7B07f33A8B32118C
  address internal constant USDC_UNDERLYING = 0xcebA9300f2b948710d2653dD7B07f33A8B32118C;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://celoscan.io/address/0xFF8309b9e99bfd2D4021bc71a362aBD93dBd4785
  address internal constant USDC_A_TOKEN = 0xFF8309b9e99bfd2D4021bc71a362aBD93dBd4785;

  // https://celoscan.io/address/0xDbe517c0FA6467873B684eCcbED77217E471E862
  address internal constant USDC_V_TOKEN = 0xDbe517c0FA6467873B684eCcbED77217E471E862;

  // https://celoscan.io/address/0xBF704f2FfdB856805cE64D085cD50427823696D7
  address internal constant USDC_ORACLE = 0xBF704f2FfdB856805cE64D085cD50427823696D7;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;

  // https://celoscan.io/address/0xba3ae0F0A78579a5e8C4188dcde60DcCc0Dd4Fab
  address internal constant USDC_STATA_TOKEN = 0xba3ae0F0A78579a5e8C4188dcde60DcCc0Dd4Fab;

  // https://celoscan.io/address/0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e
  address internal constant USDT_UNDERLYING = 0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://celoscan.io/address/0xDeE98402A302e4D707fB9bf2bac66fAEEc31e8Df
  address internal constant USDT_A_TOKEN = 0xDeE98402A302e4D707fB9bf2bac66fAEEc31e8Df;

  // https://celoscan.io/address/0xE15324a9887999803b931Ac45aa89a94A9750052
  address internal constant USDT_V_TOKEN = 0xE15324a9887999803b931Ac45aa89a94A9750052;

  // https://celoscan.io/address/0x6e3d991C965364481796116dE68A8036d1b3Ecd0
  address internal constant USDT_ORACLE = 0x6e3d991C965364481796116dE68A8036d1b3Ecd0;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;

  // https://celoscan.io/address/0x5264B1F45616dB619Bb3c8DCeBD86fB33FA0e53F
  address internal constant USDT_STATA_TOKEN = 0x5264B1F45616dB619Bb3c8DCeBD86fB33FA0e53F;

  // https://celoscan.io/address/0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73
  address internal constant cEUR_UNDERLYING = 0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73;

  uint8 internal constant cEUR_DECIMALS = 18;

  // https://celoscan.io/address/0x34c02571094e08E935B8cf8dC10F1Ad6795f1f81
  address internal constant cEUR_A_TOKEN = 0x34c02571094e08E935B8cf8dC10F1Ad6795f1f81;

  // https://celoscan.io/address/0x5C2B7EB5886B3cEc5CCE1019E34493da33291aF5
  address internal constant cEUR_V_TOKEN = 0x5C2B7EB5886B3cEc5CCE1019E34493da33291aF5;

  // https://celoscan.io/address/0x3D207061Dbe8E2473527611BFecB87Ff12b28dDa
  address internal constant cEUR_ORACLE = 0x3D207061Dbe8E2473527611BFecB87Ff12b28dDa;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant cEUR_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;

  // https://celoscan.io/address/0x765DE816845861e75A25fCA122bb6898B8B1282a
  address internal constant cUSD_UNDERLYING = 0x765DE816845861e75A25fCA122bb6898B8B1282a;

  uint8 internal constant cUSD_DECIMALS = 18;

  // https://celoscan.io/address/0xBba98352628B0B0c4b40583F593fFCb630935a45
  address internal constant cUSD_A_TOKEN = 0xBba98352628B0B0c4b40583F593fFCb630935a45;

  // https://celoscan.io/address/0x05Ee3d1fBACbDbA1259946033cd7A42FDFcCcF0d
  address internal constant cUSD_V_TOKEN = 0x05Ee3d1fBACbDbA1259946033cd7A42FDFcCcF0d;

  // https://celoscan.io/address/0xdCdA3E7E90fe827776b8FDaEa3C5977F123354DA
  address internal constant cUSD_ORACLE = 0xdCdA3E7E90fe827776b8FDaEa3C5977F123354DA;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant cUSD_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;

  // https://celoscan.io/address/0x471EcE3750Da237f93B8E339c536989b8978a438
  address internal constant CELO_UNDERLYING = 0x471EcE3750Da237f93B8E339c536989b8978a438;

  uint8 internal constant CELO_DECIMALS = 18;

  // https://celoscan.io/address/0xC3e77dC389537Db1EEc7C33B95Cf3beECA71A209
  address internal constant CELO_A_TOKEN = 0xC3e77dC389537Db1EEc7C33B95Cf3beECA71A209;

  // https://celoscan.io/address/0xaEa37B42955De2Ba2E4AF6581E46349bCD3Ea2d6
  address internal constant CELO_V_TOKEN = 0xaEa37B42955De2Ba2E4AF6581E46349bCD3Ea2d6;

  // https://celoscan.io/address/0x0568fD19986748cEfF3301e55c0eb1E729E0Ab7e
  address internal constant CELO_ORACLE = 0x0568fD19986748cEfF3301e55c0eb1E729E0Ab7e;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant CELO_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;

  // https://celoscan.io/address/0xD221812de1BD094f35587EE8E174B07B6167D9Af
  address internal constant WETH_UNDERLYING = 0xD221812de1BD094f35587EE8E174B07B6167D9Af;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://celoscan.io/address/0xf385280F36e009C157697D25E0B802EfaBfd789c
  address internal constant WETH_A_TOKEN = 0xf385280F36e009C157697D25E0B802EfaBfd789c;

  // https://celoscan.io/address/0x6508cff7c5FbA053Af00a4E894500e6fA00274B7
  address internal constant WETH_V_TOKEN = 0x6508cff7c5FbA053Af00a4E894500e6fA00274B7;

  // https://celoscan.io/address/0x1FcD30A73D67639c1cD89ff5746E7585731c083B
  address internal constant WETH_ORACLE = 0x1FcD30A73D67639c1cD89ff5746E7585731c083B;

  // https://celoscan.io/address/0x8B62D241Bf59f40991DCd18531683156d7013355
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x8B62D241Bf59f40991DCd18531683156d7013355;
}
library AaveV3CeloEModes {
  uint8 internal constant NONE = 0;
}
library AaveV3CeloExternalLibraries {
  // https://celoscan.io/address/0x5e84CEe2afb7B37d2AB14722C39A7c1C26F5B0BB
  address internal constant FLASHLOAN_LOGIC = 0x5e84CEe2afb7B37d2AB14722C39A7c1C26F5B0BB;

  // https://celoscan.io/address/0xFeD9871528E713B5038c4c44BbE7a315f56cAdc6
  address internal constant BORROW_LOGIC = 0xFeD9871528E713B5038c4c44BbE7a315f56cAdc6;

  // https://celoscan.io/address/0xD1bddC05A3BB5A7907d82A1b4F1E21dBCE69c3d5
  address internal constant E_MODE_LOGIC = 0xD1bddC05A3BB5A7907d82A1b4F1E21dBCE69c3d5;

  // https://celoscan.io/address/0x36Ae486289bB807C3C79A1427b9c3D934294ef43
  address internal constant LIQUIDATION_LOGIC = 0x36Ae486289bB807C3C79A1427b9c3D934294ef43;

  // https://celoscan.io/address/0xE51B69e5722Bf547866A4d7Bc190c6e81b626806
  address internal constant POOL_LOGIC = 0xE51B69e5722Bf547866A4d7Bc190c6e81b626806;

  // https://celoscan.io/address/0x034Fd14b9Ae6bB066a1F9f85A55e990b0b25c168
  address internal constant SUPPLY_LOGIC = 0x034Fd14b9Ae6bB066a1F9f85A55e990b0b25c168;
}
