// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3Linea {
  // https://lineascan.build/address/0x89502c3731F69DDC95B65753708A07F8Cd0373F4
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x89502c3731F69DDC95B65753708A07F8Cd0373F4);

  // https://lineascan.build/address/0xc47b8C00b0f69a36fa203Ffeac0334874574a8Ac
  IPool internal constant POOL = IPool(0xc47b8C00b0f69a36fa203Ffeac0334874574a8Ac);

  // https://lineascan.build/address/0x812E7c19421D9f41A6DDCF047d5cc2dE2Ca5Bfa2
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x812E7c19421D9f41A6DDCF047d5cc2dE2Ca5Bfa2);

  // https://lineascan.build/address/0xCFDAdA7DCd2e785cF706BaDBC2B8Af5084d595e9
  IAaveOracle internal constant ORACLE = IAaveOracle(0xCFDAdA7DCd2e785cF706BaDBC2B8Af5084d595e9);

  // https://lineascan.build/address/0x8c2d95FE7aeB57b86961F3abB296A54f0ADb7F88
  address internal constant ACL_ADMIN = 0x8c2d95FE7aeB57b86961F3abB296A54f0ADb7F88;

  // https://lineascan.build/address/0xbf32c7dFC72b730967072B112927ca0de205dbb5
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xbf32c7dFC72b730967072B112927ca0de205dbb5);

  // https://lineascan.build/address/0x47cd4b507B81cB831669c71c7077f4daF6762FF4
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x47cd4b507B81cB831669c71c7077f4daF6762FF4);

  // https://lineascan.build/address/0xF1597757c7D88e72E3778606277aaB514166cf3d
  address internal constant POOL_IMPL = 0xF1597757c7D88e72E3778606277aaB514166cf3d;

  // https://lineascan.build/address/0x10efD3d5C0578c426D2960eeF0153C446Dd6C6FA
  address internal constant POOL_CONFIGURATOR_IMPL = 0x10efD3d5C0578c426D2960eeF0153C446Dd6C6FA;

  // https://lineascan.build/address/0xc67bb8F2314fA0df50cBa314c6509A7bdAD500C0
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0xc67bb8F2314fA0df50cBa314c6509A7bdAD500C0;

  // https://lineascan.build/address/0x0165C65FB21bDC9Cdc09C627d62AB3a983337158
  address internal constant EMISSION_MANAGER = 0x0165C65FB21bDC9Cdc09C627d62AB3a983337158;

  // https://lineascan.build/address/0x86E2938daE289763D4e09a7e42c5cCcA62Cf9809
  ICollector internal constant COLLECTOR = ICollector(0x86E2938daE289763D4e09a7e42c5cCcA62Cf9809);

  // https://lineascan.build/address/0x45338b98572C67c28425bBa5Af6120719aAE8492
  address internal constant DEFAULT_A_TOKEN_IMPL = 0x45338b98572C67c28425bBa5Af6120719aAE8492;

  // https://lineascan.build/address/0x9B7f1be0bAAE6E9483dd15F37cC92cb769D12f1e
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0x9B7f1be0bAAE6E9483dd15F37cC92cb769D12f1e;

  // https://lineascan.build/address/0x1ADD95d62E2B49AF12dDf112B8D4D3B912421087
  address internal constant CONFIG_ENGINE = 0x1ADD95d62E2B49AF12dDf112B8D4D3B912421087;

  // https://lineascan.build/address/0xBDF2e1A49894A306Eb76b89504928b3f509A3a16
  address internal constant RISK_STEWARD = 0xBDF2e1A49894A306Eb76b89504928b3f509A3a16;

  // https://lineascan.build/address/0x96dFCCB3F9ACDaF6c8f8a35E814023C3484d1eA2
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0x96dFCCB3F9ACDaF6c8f8a35E814023C3484d1eA2;

  // https://lineascan.build/address/0x117684358D990E42Eb1649E7e8C4691951dc1E71
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x117684358D990E42Eb1649E7e8C4691951dc1E71;

  // https://lineascan.build/address/0xf751969521E20A972A0776CDB0497Fad0F773F1F
  address internal constant UI_POOL_DATA_PROVIDER = 0xf751969521E20A972A0776CDB0497Fad0F773F1F;

  // https://lineascan.build/address/0xff75B6da14FfbbfD355Daf7a2731456b3562Ba6D
  address internal constant WALLET_BALANCE_PROVIDER = 0xff75B6da14FfbbfD355Daf7a2731456b3562Ba6D;

  // https://lineascan.build/address/0x31A239f3e39c5D8BA6B201bA81ed584492Ae960F
  address internal constant WETH_GATEWAY = 0x31A239f3e39c5D8BA6B201bA81ed584492Ae960F;

  // https://lineascan.build/address/0x94756B7508631509601a5555c93457Bf0ebDbC48
  address internal constant DUST_BIN = 0x94756B7508631509601a5555c93457Bf0ebDbC48;

  // https://lineascan.build/address/0xA68A0864F304b5145f00A3f8Fd3ec2281568700F
  address internal constant CLINIC_STEWARD = 0xA68A0864F304b5145f00A3f8Fd3ec2281568700F;

  // https://lineascan.build/address/0x07Fc6Fa43Cf6b08d24679ebf8060386b4D41B702
  address internal constant POOL_EXPOSURE_STEWARD = 0x07Fc6Fa43Cf6b08d24679ebf8060386b4D41B702;

  // https://lineascan.build/address/0xc25Da0Ddab750739d2500dfD4E31EB4E83622F54
  address internal constant STATA_FACTORY = 0xc25Da0Ddab750739d2500dfD4E31EB4E83622F54;
}
library AaveV3LineaAssets {
  // https://lineascan.build/address/0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f
  address internal constant WETH_UNDERLYING = 0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://lineascan.build/address/0x787897dF92703BB3Fc4d9Ee98e15C0b8130Bf163
  address internal constant WETH_A_TOKEN = 0x787897dF92703BB3Fc4d9Ee98e15C0b8130Bf163;

  // https://lineascan.build/address/0x0e7543a9dA61b2E71fC880685eD2945B7426a689
  address internal constant WETH_V_TOKEN = 0x0e7543a9dA61b2E71fC880685eD2945B7426a689;

  // https://lineascan.build/address/0x3c6Cd9Cc7c7a4c2Cf5a82734CD249D7D593354dA
  address internal constant WETH_ORACLE = 0x3c6Cd9Cc7c7a4c2Cf5a82734CD249D7D593354dA;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4
  address internal constant WBTC_UNDERLYING = 0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://lineascan.build/address/0x37f7E06359F98162615e016d0008023D910bB576
  address internal constant WBTC_A_TOKEN = 0x37f7E06359F98162615e016d0008023D910bB576;

  // https://lineascan.build/address/0x74A1b56f5137b00AA0ADA1dD964a3A361Ecc32e9
  address internal constant WBTC_V_TOKEN = 0x74A1b56f5137b00AA0ADA1dD964a3A361Ecc32e9;

  // https://lineascan.build/address/0x7A99092816C8BD5ec8ba229e3a6E6Da1E628E1F9
  address internal constant WBTC_ORACLE = 0x7A99092816C8BD5ec8ba229e3a6E6Da1E628E1F9;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0x176211869cA2b568f2A7D4EE941E073a821EE1ff
  address internal constant USDC_UNDERLYING = 0x176211869cA2b568f2A7D4EE941E073a821EE1ff;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://lineascan.build/address/0x374D7860c4f2f604De0191298dD393703Cce84f3
  address internal constant USDC_A_TOKEN = 0x374D7860c4f2f604De0191298dD393703Cce84f3;

  // https://lineascan.build/address/0x63aB166e6E1b6Fb705b6ca23686FaD9705EB3534
  address internal constant USDC_V_TOKEN = 0x63aB166e6E1b6Fb705b6ca23686FaD9705EB3534;

  // https://lineascan.build/address/0x14ac9f8a8646D11D66fbaA9E9F5A869dC08B5D71
  address internal constant USDC_ORACLE = 0x14ac9f8a8646D11D66fbaA9E9F5A869dC08B5D71;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0xA219439258ca9da29E9Cc4cE5596924745e12B93
  address internal constant USDT_UNDERLYING = 0xA219439258ca9da29E9Cc4cE5596924745e12B93;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://lineascan.build/address/0x88231dfEC71D4FF5c1e466D08C321944A7adC673
  address internal constant USDT_A_TOKEN = 0x88231dfEC71D4FF5c1e466D08C321944A7adC673;

  // https://lineascan.build/address/0x4CEdfa47F7d0e9036110B850Ce49f4cd47b28a2F
  address internal constant USDT_V_TOKEN = 0x4CEdfa47F7d0e9036110B850Ce49f4cd47b28a2F;

  // https://lineascan.build/address/0x0DccbA847D677d4dc3c22C9Dc17DC468226d08Ed
  address internal constant USDT_ORACLE = 0x0DccbA847D677d4dc3c22C9Dc17DC468226d08Ed;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F
  address internal constant wstETH_UNDERLYING = 0xB5beDd42000b71FddE22D3eE8a79Bd49A568fC8F;

  uint8 internal constant wstETH_DECIMALS = 18;

  // https://lineascan.build/address/0x58943d20e010d9E34C4511990e232783460d0219
  address internal constant wstETH_A_TOKEN = 0x58943d20e010d9E34C4511990e232783460d0219;

  // https://lineascan.build/address/0x81C1a619Be23050B3242B41a739e6B6CfDa56687
  address internal constant wstETH_V_TOKEN = 0x81C1a619Be23050B3242B41a739e6B6CfDa56687;

  // https://lineascan.build/address/0x96014CA32e2902A5F07c6ADF00eB17D3DE9aC364
  address internal constant wstETH_ORACLE = 0x96014CA32e2902A5F07c6ADF00eB17D3DE9aC364;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant wstETH_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0x2416092f143378750bb29b79eD961ab195CcEea5
  address internal constant ezETH_UNDERLYING = 0x2416092f143378750bb29b79eD961ab195CcEea5;

  uint8 internal constant ezETH_DECIMALS = 18;

  // https://lineascan.build/address/0x935EfCBeFc1dF0541aFc3fE145134f8c9a0beB89
  address internal constant ezETH_A_TOKEN = 0x935EfCBeFc1dF0541aFc3fE145134f8c9a0beB89;

  // https://lineascan.build/address/0x1fE3452CEF885724F8aDF1382ee17d05d7e01CaB
  address internal constant ezETH_V_TOKEN = 0x1fE3452CEF885724F8aDF1382ee17d05d7e01CaB;

  // https://lineascan.build/address/0x1217a8A40cea4dB5429fbF6EDeB3B606b99CC9b0
  address internal constant ezETH_ORACLE = 0x1217a8A40cea4dB5429fbF6EDeB3B606b99CC9b0;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant ezETH_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0x1Bf74C010E6320bab11e2e5A532b5AC15e0b8aA6
  address internal constant weETH_UNDERLYING = 0x1Bf74C010E6320bab11e2e5A532b5AC15e0b8aA6;

  uint8 internal constant weETH_DECIMALS = 18;

  // https://lineascan.build/address/0x0C7921aB4888fd06731898b3fffFeB06781D5F4F
  address internal constant weETH_A_TOKEN = 0x0C7921aB4888fd06731898b3fffFeB06781D5F4F;

  // https://lineascan.build/address/0x37a843725508243952950307CeacE7A9f5D5c280
  address internal constant weETH_V_TOKEN = 0x37a843725508243952950307CeacE7A9f5D5c280;

  // https://lineascan.build/address/0x0abf2f5642d945b49B8d2DBC6f85c2D8e0424C85
  address internal constant weETH_ORACLE = 0x0abf2f5642d945b49B8d2DBC6f85c2D8e0424C85;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant weETH_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;

  // https://lineascan.build/address/0xD2671165570f41BBB3B0097893300b6EB6101E6C
  address internal constant wrsETH_UNDERLYING = 0xD2671165570f41BBB3B0097893300b6EB6101E6C;

  uint8 internal constant wrsETH_DECIMALS = 18;

  // https://lineascan.build/address/0xCDD80E6211FC767352B198f827200C7e93d7Bb04
  address internal constant wrsETH_A_TOKEN = 0xCDD80E6211FC767352B198f827200C7e93d7Bb04;

  // https://lineascan.build/address/0xf3C806a402E4E9101373F76C05880EEAc91BB5b9
  address internal constant wrsETH_V_TOKEN = 0xf3C806a402E4E9101373F76C05880EEAc91BB5b9;

  // https://lineascan.build/address/0x444f25c5E73fED92B91F3ECB1bD27003C3CDdeE7
  address internal constant wrsETH_ORACLE = 0x444f25c5E73fED92B91F3ECB1bD27003C3CDdeE7;

  // https://lineascan.build/address/0xB1532b76D054c9F9E61b25c4d91f69B4133E4671
  address internal constant wrsETH_INTEREST_RATE_STRATEGY =
    0xB1532b76D054c9F9E61b25c4d91f69B4133E4671;
}
library AaveV3LineaEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant WSTETH_CORRELATED = 1;

  uint8 internal constant EZETH_CORRELATED = 2;

  uint8 internal constant WEETH_CORRELATED = 3;

  uint8 internal constant WRSETH_WETH_ISOLATED_LIQUID_E_MODE = 4;
}
library AaveV3LineaExternalLibraries {
  // https://lineascan.build/address/0xb5656eCAE657A1bF5f7F5CD06363090A4D2c68e3
  address internal constant FLASHLOAN_LOGIC = 0xb5656eCAE657A1bF5f7F5CD06363090A4D2c68e3;

  // https://lineascan.build/address/0x46464bCF5BBa29834b57E6c7631fEfb966F427A2
  address internal constant BORROW_LOGIC = 0x46464bCF5BBa29834b57E6c7631fEfb966F427A2;

  // https://lineascan.build/address/0x9D147ED046EA1c629B6e66b0504E45019B133aa4
  address internal constant E_MODE_LOGIC = 0x9D147ED046EA1c629B6e66b0504E45019B133aa4;

  // https://lineascan.build/address/0x22B38029a2B034340B695C6144B3AfD678e109E3
  address internal constant LIQUIDATION_LOGIC = 0x22B38029a2B034340B695C6144B3AfD678e109E3;

  // https://lineascan.build/address/0xbB6558a80Ed7811bd6d02bD26814e49c349b3acD
  address internal constant POOL_LOGIC = 0xbB6558a80Ed7811bd6d02bD26814e49c349b3acD;

  // https://lineascan.build/address/0x330a2C27fCE66685d87ebaE4cE9dA71D2F6D1141
  address internal constant SUPPLY_LOGIC = 0x330a2C27fCE66685d87ebaE4cE9dA71D2F6D1141;
}
