// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library GhoBase {
  // https://basescan.org/address/0x6Bb7a212910682DCFdbd5BCBb3e28FB4E8da10Ee
  address internal constant GHO_TOKEN = 0x6Bb7a212910682DCFdbd5BCBb3e28FB4E8da10Ee;

  // https://basescan.org/address/0x98217A06721Ebf727f2C8d9aD7718ec28b7aAe34
  address internal constant GHO_CCIP_TOKEN_POOL = 0x98217A06721Ebf727f2C8d9aD7718ec28b7aAe34;

  // https://basescan.org/address/0xC5BcC58BE6172769ca1a78B8A45752E3C5059c39
  address internal constant GHO_AAVE_CORE_STEWARD = 0xC5BcC58BE6172769ca1a78B8A45752E3C5059c39;

  // https://basescan.org/address/0x3c47237479e7569653eF9beC4a7Cd2ee3F78b396
  address internal constant GHO_BUCKET_STEWARD = 0x3c47237479e7569653eF9beC4a7Cd2ee3F78b396;

  // https://basescan.org/address/0xB94Ab28c6869466a46a42abA834ca2B3cECCA5eB
  address internal constant GHO_CCIP_STEWARD = 0xB94Ab28c6869466a46a42abA834ca2B3cECCA5eB;
}
