// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
import {} from './GovernanceV3.sol';

library GovernanceV3XLayer {
    // https://www.oklink.com/xlayer/address/0xeB55A63bf9993d80c86D47f819B5eC958c7C127B
address internal constant GOVERNANCE_GUARDIAN = 0xeB55A63bf9993d80c86D47f819B5eC958c7C127B;

  }