// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
import {IGovernanceCore, IPayloadsControllerCore} from './GovernanceV3.sol';

library GovernanceV3Arbitrum {
  // https://arbiscan.io/address/0xCbFB78a3Eeaa611b826E37c80E4126c8787D29f0
  address internal constant CROSS_CHAIN_CONTROLLER = 0xCbFB78a3Eeaa611b826E37c80E4126c8787D29f0;
}
