// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscBaseSepolia {
  // https://sepolia.basescan.org/address/0x95F99D1695c866FEb16657cCA8E91437a50D2a5e
  address internal constant TRANSPARENT_PROXY_FACTORY = 0x95F99D1695c866FEb16657cCA8E91437a50D2a5e;

  // https://sepolia.basescan.org/address/0x6CBc6928Ad317F60E8880C43479850F2190F2a0B
  address internal constant PROXY_ADMIN = 0x6CBc6928Ad317F60E8880C43479850F2190F2a0B;

  // https://sepolia.basescan.org/address/0xD9145b5F45Ad4519c7ACcD6E0A4A82e83bB8A6Dc
  address internal constant FAUCET = 0xD9145b5F45Ad4519c7ACcD6E0A4A82e83bB8A6Dc;
}
