// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscXLayer {
  // https://www.oklink.com/xlayer/address/0xF6Dac650dA5616Bc3206e969D7868e7c25805171
  address internal constant TRANSPARENT_PROXY_FACTORY = 0xF6Dac650dA5616Bc3206e969D7868e7c25805171;

  // https://www.oklink.com/xlayer/address/0xD0D1CcB0391aADF1EaD96814ce7ab4008Ebdb336
  address internal constant PROTOCOL_GUARDIAN = 0xD0D1CcB0391aADF1EaD96814ce7ab4008Ebdb336;

  // https://www.oklink.com/xlayer/address/0x66Ac7223048037826e12cef9a848199e31AEFabE
  address internal constant BUDGET_INCENTIVE_SAFE = 0x66Ac7223048037826e12cef9a848199e31AEFabE;

  // https://www.oklink.com/xlayer/address/0x89587ebe7cFF64c6527fE2Deccc3521D75763E8D
  address internal constant MERKL_DISTRIBUTION_SAFE = 0x89587ebe7cFF64c6527fE2Deccc3521D75763E8D;

  // https://www.oklink.com/xlayer/address/0x441E4053fDDF1e1a77a39d00309Af389096d4124
  address internal constant ROBOT_GUARDIAN = 0x441E4053fDDF1e1a77a39d00309Af389096d4124;
}
