// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscCelo {
  // https://explorer.celo.org/mainnet/address/0xb172a90A7C238969CE9B27cc19D13b60A91e7F00
  address internal constant TRANSPARENT_PROXY_FACTORY = 0xb172a90A7C238969CE9B27cc19D13b60A91e7F00;

  // https://explorer.celo.org/mainnet/address/0x38BC0ED9d90Bc2309A436f4ED6Ca6Bc4D5C0DFA6
  address internal constant PROTOCOL_GUARDIAN = 0x38BC0ED9d90Bc2309A436f4ED6Ca6Bc4D5C0DFA6;

  // https://explorer.celo.org/mainnet/address/0x01d678F1bbE148C96e7501F1Ac41661904F84F61
  address internal constant PROXY_ADMIN = 0x01d678F1bbE148C96e7501F1Ac41661904F84F61;
}
