// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscScroll {
  // https://scrollscan.com/address/0xFa2eeb2d0054C3Db2A606E2cd9EE111b62707D1e
  address internal constant TRANSPARENT_PROXY_FACTORY = 0xFa2eeb2d0054C3Db2A606E2cd9EE111b62707D1e;

  // https://scrollscan.com/address/0x782559e349b084bB7C07c08404aE6E3436cDAE2E
  address internal constant PROXY_ADMIN = 0x782559e349b084bB7C07c08404aE6E3436cDAE2E;
}
