// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscFuji {
  // https://testnet.snowtrace.io/address/0x9c04928Cc678776eC1C1C0E46ecC03a5F47A7723
  address internal constant GHO_TOKEN = 0x9c04928Cc678776eC1C1C0E46ecC03a5F47A7723;

  // https://testnet.snowtrace.io/address/0x421117D7319E96d831972b3F7e970bbfe29C4F21
  address internal constant TRANSPARENT_PROXY_FACTORY = 0x421117D7319E96d831972b3F7e970bbfe29C4F21;

  // https://testnet.snowtrace.io/address/0xd6a6339c6C1B5a8792afA6e0E80b1908b8579f51
  address internal constant PROXY_ADMIN = 0xd6a6339c6C1B5a8792afA6e0E80b1908b8579f51;

  // https://testnet.snowtrace.io/address/0x48B5bD96e36a9c0D0eA3f07d3b3dA34bBD514fB3
  address internal constant FAUCET = 0x48B5bD96e36a9c0D0eA3f07d3b3dA34bBD514fB3;
}
