// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IUmbrella} from './common/IUmbrella.sol';

library UmbrellaEthereum {
  // https://etherscan.io/address/0xD400fc38ED4732893174325693a63C30ee3881a8
  IUmbrella internal constant UMBRELLA = IUmbrella(0xD400fc38ED4732893174325693a63C30ee3881a8);

  // https://etherscan.io/address/0x929e21D24D3f2A529621AdC248D227012B72646d
  address internal constant UMBRELLA_IMPL = 0x929e21D24D3f2A529621AdC248D227012B72646d;

  // https://etherscan.io/address/0x75e8aC0c063B6966E2A9954adEdf39BdE9370197
  address internal constant UMBRELLA_STAKE_TOKEN_IMPL = 0x75e8aC0c063B6966E2A9954adEdf39BdE9370197;

  // https://etherscan.io/address/0x4655Ce3D625a63d30bA704087E52B4C31E38188B
  address internal constant UMBRELLA_REWARDS_CONTROLLER =
    0x4655Ce3D625a63d30bA704087E52B4C31E38188B;

  // https://etherscan.io/address/0x85C3371044e49782DbE3dC23de1D77a078aFb5d0
  address internal constant UMBRELLA_REWARDS_CONTROLLER_IMPL =
    0x85C3371044e49782DbE3dC23de1D77a078aFb5d0;

  // https://etherscan.io/address/0xF86F77F7531B3374274E3f725E0A81D60bC4bB67
  address internal constant PERMISSIONED_PAYLOADS_CONTROLLER =
    0xF86F77F7531B3374274E3f725E0A81D60bC4bB67;

  // https://etherscan.io/address/0x2759de67aD133C747C9f41d56F1b8A343cE679a1
  address internal constant PERMISSIONED_PAYLOADS_CONTROLLER_EXECUTOR =
    0x2759de67aD133C747C9f41d56F1b8A343cE679a1;

  // https://etherscan.io/address/0xCe6Ced23118EDEb23054E06118a702797b13fc2F
  address internal constant UMBRELLA_BATCH_HELPER = 0xCe6Ced23118EDEb23054E06118a702797b13fc2F;

  // https://etherscan.io/address/0x21f01c82Bc205c2A6F20E6694fd912cBccdcA208
  address internal constant UMBRELLA_CONFIG_ENGINE = 0x21f01c82Bc205c2A6F20E6694fd912cBccdcA208;

  // https://etherscan.io/address/0xAeB694261D4A36A060974044fB1f2d15CFB7851b
  address internal constant DATA_AGGREGATION_HELPER = 0xAeB694261D4A36A060974044fB1f2d15CFB7851b;

  // https://etherscan.io/address/0x6c1DC85f2aE71C3DAcd6E44Bb57DEeF61b540a5A
  address internal constant DEFICIT_OFFSET_CLINIC_STEWARD =
    0x6c1DC85f2aE71C3DAcd6E44Bb57DEeF61b540a5A;
}
library UmbrellaEthereumAssets {}
