name: PR Comment

on:
  workflow_run:
    workflows: [ Test ]
    types:
      - completed

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@130a99a60ad2c4944ab6114105d86fcbb841af77 # pin@main
