name: PR Comment

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@ea41920d7c7c656823137da415d1e3f59bf064bf # pin@main
    secrets: inherit
