name: PR Comment

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@1762723929c79ec9d11b813f03968e39dbbbe082 # pin@main
