name: Ipfs uploader
# Uploads all changed svg files to ipfs once merged to main

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main

jobs:
  ipfs-upload:
    runs-on: ubuntu-latest
    name: Ipfs uploader
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get all changed *.svg file(s)
        id: changed-files
        uses: tj-actions/changed-files@f569b77fb1d9ad9f1a125757d7e9e07b1f320199
        with:
          json: true
          write_output_files: true
          files: |
            assets/**/*.svg

      - name: Run step if any *.md file(s) change
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cat .github/outputs/all_changed_files.json

      - name: Upload
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          PINATA_KEY: ${{ secrets.PINATA_KEY }}
          PINATA_SECRET: ${{ secrets.PINATA_SECRET }}
        run: |
          json_array=($(jq -r '.[]' ".github/outputs/all_changed_files.json"))
          for i in "${json_array[@]}"
          do
            yarn ci:upload $i
          done
