name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  pkg-size-report:
    permissions:
      pull-requests: write
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v3

      - uses: aave-dao/github-workflows/.github/actions/setup-node@main

      - name: Package size report
        uses: aave-dao/github-workflows/.github/actions/size-limit@1c90ddbb97f3dbad62b97b656e9f7b68b2da8747 # pin@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_delta: 2
